import React,{useEffect,useMemo,useState} from 'react';
import QRCode from 'qrcode';
import { Cable, CheckCircle2, Clock3, CreditCard, RefreshCw, Save, ShieldCheck, Smartphone, Webhook, Zap, QrCode } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import { EmptyState, PageHeader, StatusBadge } from '../ui/ProUi';

const integrationState=(cfg:any)=>{
 if(!cfg)return {label:'NÃO CONFIGURADO',tone:'warning' as const};
 const test=String(cfg.last_test_status||'').toUpperCase();
 if(test.includes('ERROR')||test.includes('FAIL'))return {label:'ERRO',tone:'danger' as const};
 if(cfg.enabled&&(test.includes('OK')||test.includes('SUCCESS')||test.includes('CONNECTED')))return {label:'CONECTADO',tone:'success' as const};
 if(cfg.enabled)return {label:'HOMOLOGAÇÃO PENDENTE',tone:'warning' as const};
 return {label:'CONFIGURANDO',tone:'info' as const};
};

const providers=[
 {id:'IFOOD',name:'iFood',desc:'Pedidos, catálogo e delivery após homologação.',tone:'bg-red-600',icon:Smartphone},
 {id:'ASAAS',name:'Asaas',desc:'PIX, cobrança e recorrência via API/webhook.',tone:'bg-blue-700',icon:CreditCard},
 {id:'PAGSEGURO',name:'PagSeguro',desc:'Pagamentos e terminais conforme produto homologado.',tone:'bg-emerald-700',icon:CreditCard},
 {id:'MERCADO_PAGO',name:'Mercado Pago',desc:'PIX e pagamentos digitais via integração oficial.',tone:'bg-sky-700',icon:Zap},
 {id:'CARD_TERMINAL',name:'SmartPOS / TEF',desc:'Envio do valor ao terminal depende de provedor homologado.',tone:'bg-amber-600',icon:CreditCard},
 {id:'FISCAL',name:'NFC-e / Fiscal',desc:'Certificado, CSC e transmissão devem permanecer no backend.',tone:'bg-violet-700',icon:ShieldCheck}
];

export const ProductionIntegrationsView:React.FC=()=>{
 const[pix,setPix]=useState<any>(null);const[pixQr,setPixQr]=useState('');const[configs,setConfigs]=useState<any[]>([]);const[provider,setProvider]=useState('CARD_TERMINAL');const[url,setUrl]=useState('');const[events,setEvents]=useState('payment.approved,payment.failed,receipt.ready');const[authMode,setAuthMode]=useState<'NONE'|'HMAC'|'BEARER'|'BASIC'>('HMAC');const[secretRef,setSecretRef]=useState('');const[enabled,setEnabled]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const [c,p]=await Promise.all([productionDb.getIntegrationWebhookConfigs(),productionDb.getPixConfig()]);setConfigs(c);setPix(p||{pix_key:'',pix_key_type:'OTHER',merchant_name:'',merchant_city:'',enabled:true});}catch(e:any){setError(e?.message||'Falha ao carregar webhooks.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const configured=useMemo(()=>new Map(configs.map(c=>[String(c.provider).toUpperCase(),c])),[configs]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{await productionDb.saveIntegrationWebhookConfig({provider,webhookUrl:url,eventTypes:events.split(',').map(x=>x.trim()).filter(Boolean),authMode,secretRef:secretRef.trim()||undefined,enabled});setMessage('Configuração salva. O segredo real permanece fora do navegador; aqui é armazenada somente a referência.');await load();}catch(err:any){setError(err?.message||'Não foi possível salvar o webhook.');}finally{setBusy(false);}};
 const selectProvider=(id:string)=>{setProvider(id);const cfg=configured.get(id);setUrl(cfg?.webhook_url||'');setEvents(Array.isArray(cfg?.event_types)?cfg.event_types.join(','):'payment.approved,payment.failed,receipt.ready');setAuthMode((cfg?.auth_mode||'HMAC') as any);setSecretRef(cfg?.secret_ref||'');setEnabled(Boolean(cfg?.enabled));};
 const savePix=async()=>{try{setBusy(true);setError('');const p=await productionDb.savePixConfig({pixKey:pix.pix_key,pixKeyType:pix.pix_key_type,merchantName:pix.merchant_name,merchantCity:pix.merchant_city,enabled:pix.enabled});setPix(p);setPixQr(await QRCode.toDataURL(p.pix_key,{width:280,margin:2}));setMessage('PIX salvo e sincronizado com o PDV.');}catch(e:any){setError(e?.message||'Falha ao salvar PIX.')}finally{setBusy(false)}};
 useEffect(()=>{if(pix?.pix_key)QRCode.toDataURL(pix.pix_key,{width:280,margin:2}).then(setPixQr).catch(()=>setPixQr(''));},[pix?.pix_key]);
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
  <PageHeader eyebrow="Ecossistema conectado" title="Integrações" description="Conectores, webhooks e estados de homologação da loja ativa. Nenhum provedor é exibido como conectado sem configuração real." actions={<button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>{busy?'Atualizando...':'Atualizar'}</button>}/>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{message&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs flex items-center gap-2"><CheckCircle2 size={14}/>{message}</div>}
  <div className="p-4 rounded-2xl border border-emerald-800/40 bg-emerald-950/15 flex items-start gap-3"><ShieldCheck size={18} className="text-emerald-400 shrink-0"/><div><div className="text-sm font-black">Integrações isoladas por loja</div><div className="text-xs text-neutral-500 mt-1">Configurações usam o contexto autenticado do tenant/store. Segredos reais devem ficar em Vault/Edge Function e nunca no frontend.</div></div></div>
  <section className="ap-panel p-5"><div className="flex items-center gap-2"><QrCode size={18} className="text-amber-400"/><div><h2 className="font-black">PIX manual da loja</h2><p className="text-[10px] text-neutral-500">Cadastre a chave que será exibida no PDV. O operador confirma manualmente o pagamento.</p></div></div><div className="grid lg:grid-cols-[1fr_300px] gap-5 mt-4"><div className="grid md:grid-cols-2 gap-3"><label className="text-xs text-neutral-400">Tipo<select value={pix?.pix_key_type||'OTHER'} onChange={e=>setPix({...pix,pix_key_type:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"><option>CPF</option><option>CNPJ</option><option>EMAIL</option><option>PHONE</option><option>EVP</option><option>OTHER</option></select></label><label className="text-xs text-neutral-400">Chave PIX<input value={pix?.pix_key||''} onChange={e=>setPix({...pix,pix_key:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"/></label><label className="text-xs text-neutral-400">Favorecido<input value={pix?.merchant_name||''} onChange={e=>setPix({...pix,merchant_name:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"/></label><label className="text-xs text-neutral-400">Cidade<input value={pix?.merchant_city||''} onChange={e=>setPix({...pix,merchant_city:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={pix?.enabled!==false} onChange={e=>setPix({...pix,enabled:e.target.checked})}/>PIX ativo no PDV</label><button type="button" disabled={busy||!pix?.pix_key} onClick={()=>void savePix()} className="px-5 py-3 rounded-xl bg-amber-500 text-neutral-950 font-black text-sm">Salvar PIX</button></div><div className="rounded-2xl bg-white p-3 grid place-items-center min-h-[220px]">{pixQr?<img src={pixQr} alt="QR Code PIX" className="w-[220px] h-[220px]"/>:<div className="text-neutral-500 text-xs text-center">Informe a chave PIX para gerar o QR Code.</div>}</div></div></section>
  <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{providers.map(p=>{const cfg=configured.get(p.id);const state=integrationState(cfg);const I=p.icon;return <button key={p.id} onClick={()=>selectProvider(p.id)} className={`text-left p-4 rounded-2xl border transition-all ${provider===p.id?'border-amber-500/60 bg-amber-500/5':'border-neutral-800 bg-neutral-900 hover:border-neutral-700'}`}><div className="flex items-start justify-between gap-3"><div className={`w-11 h-11 rounded-xl ${p.tone} grid place-items-center text-white`}><I size={19}/></div><StatusBadge tone={state.tone}>{state.label}</StatusBadge></div><div className="mt-4 font-black">{p.name}</div><div className="text-[10px] text-neutral-500 mt-1 leading-relaxed">{p.desc}</div>{cfg?.last_test_at&&<div className="text-[9px] text-neutral-600 mt-3">Último teste {new Date(cfg.last_test_at).toLocaleString('pt-BR')}</div>}{cfg?.updated_at&&!cfg?.last_test_at&&<div className="text-[9px] text-neutral-600 mt-3">Atualizado {new Date(cfg.updated_at).toLocaleString('pt-BR')}</div>}</button>})}</div>
  <div className="grid xl:grid-cols-[1fr_.85fr] gap-4">
   <form onSubmit={save} className="ap-panel p-5 space-y-4"><div className="flex items-center gap-2"><Webhook size={18} className="text-amber-400"/><div><h2 className="font-black">Webhook / conector técnico</h2><p className="text-[10px] text-neutral-500">Configuração do provedor selecionado: {providers.find(p=>p.id===provider)?.name||provider}</p></div></div><div className="grid md:grid-cols-2 gap-3"><label className="text-xs text-neutral-400">Provedor<select value={provider} onChange={e=>selectProvider(e.target.value)} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5">{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="CUSTOM">Customizado</option></select></label><label className="text-xs text-neutral-400">URL do webhook<input required type="url" pattern="https://.*" placeholder="https://api.seudominio.com/webhooks/..." value={url} onChange={e=>setUrl(e.target.value)} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"/></label><label className="text-xs text-neutral-400 md:col-span-2">Eventos<input value={events} onChange={e=>setEvents(e.target.value)} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"/></label><label className="text-xs text-neutral-400">Autenticação<select value={authMode} onChange={e=>setAuthMode(e.target.value as any)} className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5"><option value="HMAC">HMAC</option><option value="BEARER">Bearer</option><option value="BASIC">Basic</option><option value="NONE">Nenhuma</option></select></label><label className="text-xs text-neutral-400">Referência do segredo<input value={secretRef} onChange={e=>setSecretRef(e.target.value)} placeholder="vault://integrations/provider" className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5 font-mono"/></label></div><label className="flex items-center gap-2 text-xs text-neutral-300"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Marcar configuração ativa após homologação</label><button disabled={busy} className="px-5 py-3 rounded-xl bg-amber-500 text-neutral-950 font-black text-sm flex items-center gap-2"><Save size={15}/>{busy?'Salvando...':'Salvar configuração'}</button></form>
   <section className="ap-panel p-5"><div className="flex items-center gap-2"><Clock3 size={16} className="text-amber-400"/><h2 className="font-black">Webhooks cadastrados</h2></div><div className="mt-4 space-y-2">{configs.length===0?<EmptyState title="Nenhum webhook cadastrado" description="Escolha um provedor ao lado e configure o endpoint somente quando houver credenciais e homologação."/>:configs.map(c=><div key={c.id} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800"><div className="flex justify-between gap-3"><span className="text-xs font-black">{c.provider}</span><StatusBadge tone={c.enabled?'success':'neutral'}>{c.enabled?'ATIVO':'INATIVO'}</StatusBadge></div><div className="mt-2 text-[10px] text-neutral-400 break-all">{c.webhook_url}</div><div className="mt-1 text-[9px] text-neutral-600">{Array.isArray(c.event_types)?c.event_types.join(', '):''} · {c.auth_mode}</div></div>)}</div></section>
  </div>
  <div className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800 text-xs text-neutral-500"><strong className="text-white">SmartPOS / máquina de cartão:</strong> a interface está preparada para receber um provedor homologado. O envio automático do valor e retorno de NSU/comprovante só deve ser habilitado após integração oficial e validação do webhook.</div>
 </div>;
};