import React, { useEffect, useMemo, useState } from 'react';
import { Search, ShoppingCart, Trash2, Plus, Minus, CheckCircle2, AlertTriangle } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { CashSession, Customer, Product, User } from '../../types';

interface Props { currentUser: User; currentSession?: CashSession; onNavigate: (tab:string)=>void; }
type Line={product:Product;quantity:number};

export const ProductionPosScreen:React.FC<Props>=({currentUser,currentSession,onNavigate})=>{
  const [products,setProducts]=useState<Product[]>([]); const [customers,setCustomers]=useState<Customer[]>([]);
  const [query,setQuery]=useState(''); const [cart,setCart]=useState<Line[]>([]); const [customerId,setCustomerId]=useState('');
  const [discount,setDiscount]=useState(0); const [method,setMethod]=useState<'DINHEIRO'|'PIX'|'DEBITO'|'CREDITO'|'VOUCHER'|'FIADO'>('DINHEIRO');
  const [tendered,setTendered]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const load=async()=>{try{const [p,c]=await Promise.all([productionDb.getProducts(),productionDb.getCustomers()]);setProducts(p.filter(x=>x.status==='ACTIVE'));setCustomers(c);}catch(e:any){setError(e?.message||'Falha ao carregar PDV.');}};
  useEffect(()=>{void load();},[]);
  const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return [];return products.filter(p=>p.name.toLowerCase().includes(q)||p.barcode.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)).slice(0,12);},[query,products]);
  const subtotal=cart.reduce((s,l)=>s+l.product.salePrice*l.quantity,0); const total=Math.max(0,subtotal-discount);
  const add=(p:Product)=>{if(p.isCombo){setError('Combos ainda não estão liberados em produção até o estoque de componentes ser configurado.');return;}if(p.currentStock<=0){setError('Produto sem estoque.');return;}setCart(prev=>{const hit=prev.find(x=>x.product.id===p.id);return hit?prev.map(x=>x.product.id===p.id?{...x,quantity:x.quantity+1}:x):[...prev,{product:p,quantity:1}]});setQuery('');setError('');};
  const qty=(id:string,d:number)=>setCart(prev=>prev.map(x=>x.product.id===id?{...x,quantity:Math.max(0,x.quantity+d)}:x).filter(x=>x.quantity>0));
  const finalize=async()=>{
    if(!currentSession){setError('Abra uma sessão de caixa antes de vender.');return;} if(cart.length===0||total<=0)return;
    if(method==='FIADO'&&!customerId){setError('Selecione um cliente para venda fiada.');return;}
    const amount=method==='DINHEIRO'?Number((tendered||String(total)).replace(',','.')):total;
    if(!Number.isFinite(amount)||amount<total){setError('Valor recebido insuficiente.');return;} const change=method==='DINHEIRO'?Math.max(0,amount-total):0;
    setBusy(true);setError('');setMessage('');
    try{const id=await productionDb.finalizeSale({cash_session_id:currentSession.id,customer_id:customerId||null,idempotency_key:crypto.randomUUID(),items:cart.map(l=>({product_id:l.product.id,quantity:l.quantity,discount:0})),payments:[{method,amount,change_amount:change,provider:'MANUAL'}],surcharge:0});setMessage('Venda registrada com sucesso. ID: '+String(id).slice(0,8)+'…');setCart([]);setCustomerId('');setDiscount(0);setTendered('');await load();}catch(e:any){setError(e?.message||'Venda não concluída.');}finally{setBusy(false);}
  };
  if(!currentSession)return <div className="flex-1 grid place-items-center p-6 bg-neutral-950 text-white"><div className="max-w-md p-6 rounded-2xl bg-neutral-900 border border-neutral-800 text-center"><AlertTriangle className="mx-auto text-amber-400" size={30}/><h1 className="font-black mt-3">Caixa fechado</h1><p className="text-sm text-neutral-400 mt-2">No ambiente de produção, toda venda exige sessão de caixa segura vinculada ao operador.</p><button onClick={()=>onNavigate('cash')} className="mt-4 px-5 py-2.5 rounded-xl bg-amber-500 text-neutral-950 font-black text-sm">Abrir caixa</button></div></div>;
  return <div className="flex-1 min-h-0 grid grid-cols-1 lg:grid-cols-[1fr_420px] bg-neutral-950 text-white overflow-y-auto lg:overflow-hidden">
    <section className="p-3 sm:p-4 lg:p-5 lg:overflow-y-auto border-b lg:border-b-0 lg:border-r border-neutral-800">
      <div className="flex items-center justify-between gap-3 mb-4"><div><h1 className="text-xl font-black">PDV Produção</h1><p className="text-xs text-neutral-500">Operador: {currentUser.name} · {currentSession.cashRegisterNumber}</p></div><span className="text-[10px] px-2 py-1 rounded-full border border-emerald-800 bg-emerald-950/40 text-emerald-300">TRANSAÇÃO SUPABASE</span></div>
      {error&&<div className="mb-3 p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{message&&<div className="mb-3 p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs flex items-center gap-2"><CheckCircle2 size={14}/>{message}</div>}
      <div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto por nome, EAN ou SKU..." className="w-full bg-neutral-900 border border-neutral-700 rounded-xl pl-10 pr-3 py-3 text-sm outline-none focus:border-amber-400"/></div>
      {results.length>0&&<div className="mt-2 rounded-xl border border-neutral-800 bg-neutral-900 overflow-hidden">{results.map(p=><button key={p.id} onClick={()=>add(p)} className="w-full px-4 py-3 flex justify-between gap-3 hover:bg-neutral-800 border-b border-neutral-800 text-left"><span><strong className="text-sm">{p.name}</strong><span className="block text-[11px] text-neutral-500">{p.barcode||p.sku} · estoque {p.currentStock}</span></span><span className="font-mono font-black text-amber-400">R$ {p.salePrice.toFixed(2)}</span></button>)}</div>}
      <div className="mt-5 space-y-2">{cart.length===0?<div className="py-16 text-center text-neutral-600"><ShoppingCart size={38} className="mx-auto mb-3"/><p className="text-sm">Carrinho vazio</p></div>:cart.map(l=><div key={l.product.id} className="p-3 rounded-xl border border-neutral-800 bg-neutral-900 flex items-center gap-3"><div className="min-w-0 flex-1"><div className="font-bold text-sm truncate">{l.product.name}</div><div className="text-xs text-neutral-500">R$ {l.product.salePrice.toFixed(2)} cada</div></div><div className="flex items-center gap-2"><button onClick={()=>qty(l.product.id,-1)} className="w-8 h-8 grid place-items-center rounded-lg bg-neutral-800"><Minus size={14}/></button><strong className="w-6 text-center">{l.quantity}</strong><button onClick={()=>qty(l.product.id,1)} className="w-8 h-8 grid place-items-center rounded-lg bg-neutral-800"><Plus size={14}/></button></div><div className="w-24 text-right font-mono font-black text-amber-400">R$ {(l.product.salePrice*l.quantity).toFixed(2)}</div><button onClick={()=>setCart(x=>x.filter(i=>i.product.id!==l.product.id))} className="text-rose-400"><Trash2 size={16}/></button></div>)}</div>
    </section>
    <aside className="p-4 sm:p-5 bg-neutral-900/60 lg:overflow-y-auto">
      <h2 className="font-black mb-4">Fechamento da venda</h2>
      <label className="block text-xs text-neutral-400 mb-1">Cliente</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-3 text-sm"><option value="">Consumidor não identificado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
      <label className="block text-xs text-neutral-400 mt-4 mb-1">Desconto total</label><input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(Number(e.target.value)||0)} className="w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-3 text-sm"/>
      <label className="block text-xs text-neutral-400 mt-4 mb-1">Forma de pagamento</label><select value={method} onChange={e=>setMethod(e.target.value as any)} className="w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-3 text-sm"><option value="DINHEIRO">Dinheiro</option><option value="PIX">PIX — confirmação manual</option><option value="DEBITO">Débito — confirmação manual</option><option value="CREDITO">Crédito — confirmação manual</option><option value="VOUCHER">Voucher</option><option value="FIADO">Fiado</option></select>
      {method==='DINHEIRO'&&<><label className="block text-xs text-neutral-400 mt-4 mb-1">Valor recebido</label><input value={tendered} onChange={e=>setTendered(e.target.value)} placeholder={total.toFixed(2)} className="w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-3 text-sm"/></>}
      <div className="mt-6 p-4 rounded-2xl bg-neutral-950 border border-neutral-800 space-y-2"><div className="flex justify-between text-sm text-neutral-400"><span>Subtotal</span><span>R$ {subtotal.toFixed(2)}</span></div><div className="flex justify-between text-sm text-neutral-400"><span>Desconto</span><span>- R$ {discount.toFixed(2)}</span></div><div className="flex justify-between text-xl font-black pt-3 border-t border-neutral-800"><span>Total</span><span className="text-amber-400">R$ {total.toFixed(2)}</span></div></div>
      <button disabled={busy||cart.length===0} onClick={()=>void finalize()} className="mt-4 w-full py-4 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:bg-neutral-800 disabled:text-neutral-500 font-black">{busy?'PROCESSANDO...':'FINALIZAR VENDA'}</button>
      <p className="mt-3 text-[10px] text-neutral-500 leading-relaxed">PIX e cartões são confirmação manual enquanto não houver gateway/TEF homologado. O ADEGA PRO não simula autorização financeira em produção.</p>
    </aside>
  </div>;
};