import React,{useEffect,useMemo,useState} from 'react';
import { DollarSign, RefreshCw } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
export const ProductionFinanceView:React.FC=()=>{const[rows,setRows]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
const load=async()=>{setBusy(true);setError('');try{setRows(await productionDb.getFinancialTransactions());}catch(e:any){setError(e?.message||'Falha ao carregar financeiro.');}finally{setBusy(false);}};useEffect(()=>{void load();},[]);
const totals=useMemo(()=>rows.reduce((a,r)=>{const v=Number(r.amount||0);if(r.transaction_type==='RECEITA')a.receita+=v;else a.despesa+=v;return a;},{receita:0,despesa:0}),[rows]);
return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 bg-neutral-950"><div className="flex items-start justify-between gap-3 pb-4 border-b border-neutral-800"><div><h1 className="text-xl font-black text-white flex items-center gap-2"><DollarSign size={22} className="text-amber-400"/>Financeiro Produção</h1><p className="text-xs text-neutral-400 mt-1">Lançamentos originados das transações reais do sistema.</p></div><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button></div>
{error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}<div className="grid sm:grid-cols-3 gap-3"><Card label="Receitas" value={totals.receita} cls="text-emerald-400"/><Card label="Despesas" value={totals.despesa} cls="text-rose-400"/><Card label="Saldo" value={totals.receita-totals.despesa} cls="text-amber-400"/></div>
<div className="bg-neutral-900 border border-neutral-800 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-neutral-950/70 text-neutral-400 uppercase"><tr><th className="p-3 text-left">Data</th><th className="p-3 text-left">Descrição</th><th className="p-3 text-left">Origem</th><th className="p-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-neutral-800">{rows.map(r=><tr key={r.id}><td className="p-3 text-neutral-400">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3 text-white">{r.description}</td><td className="p-3 text-neutral-400">{r.source}</td><td className={'p-3 text-right font-mono font-bold '+(r.transaction_type==='RECEITA'?'text-emerald-400':'text-rose-400')}>{r.transaction_type==='DESPESA'?'- ':''}R$ {Number(r.amount||0).toFixed(2)}</td></tr>)}</tbody></table></div></div></div>;};
const Card=({label,value,cls}:{label:string;value:number;cls:string})=><div className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><div className="text-xs text-neutral-500">{label}</div><div className={'text-2xl font-black mt-1 '+cls}>R$ {value.toFixed(2)}</div></div>;