import React,{useEffect,useMemo,useState} from 'react';
import { ArrowDownCircle, ArrowUpCircle, CalendarClock, DollarSign, RefreshCw, WalletCards } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import { EmptyState, MetricCard, PageHeader, StatusBadge } from '../ui/ProUi';

const money=(v:any)=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});

export const ProductionFinanceView:React.FC=()=>{
 const[rows,setRows]=useState<any[]>([]);const[payables,setPayables]=useState<any[]>([]);const[receivables,setReceivables]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[r,p,a]=await Promise.all([productionDb.getFinancialTransactions(),productionDb.getAccountsPayable(),productionDb.getAccountsReceivable()]);setRows(r);setPayables(p);setReceivables(a);}catch(e:any){setError(e?.message||'Falha ao carregar financeiro.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const totals=useMemo(()=>rows.reduce((a,r)=>{const v=Number(r.amount||0);if(r.transaction_type==='RECEITA')a.receita+=v;else a.despesa+=v;return a;},{receita:0,despesa:0}),[rows]);
 const ap=payables.filter(x=>['PENDENTE','ATRASADO'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0);
 const ar=receivables.filter(x=>['PENDENTE','ATRASADO'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0);
 const overdue=[...payables.map(x=>({...x,kind:'PAGAR'})),...receivables.map(x=>({...x,kind:'RECEBER'}))].filter(x=>['PENDENTE','ATRASADO'].includes(x.status)&&new Date(String(x.due_date)+'T00:00:00')<new Date(new Date().toDateString())).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date))).slice(0,8);
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
  <PageHeader eyebrow="Gestão financeira" title="Financeiro & fluxo" description="Receitas, despesas, contas a pagar e receber da loja atual." actions={<button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>{busy?'Atualizando...':'Atualizar'}</button>}/>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><MetricCard label="Receitas" value={money(totals.receita)} icon={ArrowUpCircle} tone="emerald"/><MetricCard label="Despesas" value={money(totals.despesa)} icon={ArrowDownCircle} tone="rose"/><MetricCard label="Saldo" value={money(totals.receita-totals.despesa)} icon={DollarSign} tone={(totals.receita-totals.despesa)>=0?'amber':'rose'}/><MetricCard label="A pagar" value={money(ap)} icon={CalendarClock} tone={ap?'rose':'emerald'}/><MetricCard label="A receber" value={money(ar)} icon={WalletCards} tone="violet"/></div>
  <div className="grid xl:grid-cols-[1fr_.8fr] gap-4">
   <section className="ap-panel overflow-hidden"><div className="p-4 border-b border-neutral-800"><h2 className="font-black">Movimentações financeiras</h2><p className="text-[10px] text-neutral-500 mt-1">Origem transacional e lançamentos persistidos.</p></div>{rows.length===0?<div className="p-4"><EmptyState title="Sem movimentações" description="As receitas e despesas aparecerão aqui conforme a operação registrar eventos financeiros."/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead className="bg-neutral-950 text-neutral-500 uppercase"><tr><th className="p-3 text-left">Data</th><th className="p-3 text-left">Descrição</th><th className="p-3 text-left">Origem</th><th className="p-3 text-left">Tipo</th><th className="p-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-neutral-800">{rows.map(r=><tr key={r.id} className="hover:bg-neutral-800/30"><td className="p-3 text-neutral-500">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3 text-white">{r.description}</td><td className="p-3 text-neutral-400">{r.source}</td><td className="p-3"><StatusBadge tone={r.transaction_type==='RECEITA'?'success':'danger'}>{r.transaction_type}</StatusBadge></td><td className={'p-3 text-right font-mono font-black '+(r.transaction_type==='RECEITA'?'text-emerald-400':'text-rose-400')}>{r.transaction_type==='DESPESA'?'- ':''}{money(r.amount)}</td></tr>)}</tbody></table></div>}</section>
   <section className="ap-panel p-4"><h2 className="font-black">Vencimentos e pendências</h2><p className="text-[10px] text-neutral-500 mt-1">Prioridade por data de vencimento.</p><div className="mt-4 space-y-2">{overdue.length?overdue.map(x=><div key={x.kind+x.id} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-xs font-bold truncate">{x.description||x.category||x.kind}</div><div className="text-[10px] text-neutral-500">Venc. {new Date(String(x.due_date)+'T00:00:00').toLocaleDateString('pt-BR')} · {x.kind}</div></div><div className="text-right"><StatusBadge tone="danger">{x.status==='ATRASADO'?'ATRASADO':'VENCIDO'}</StatusBadge><div className="font-mono text-xs text-rose-400 mt-1">{money(x.amount)}</div></div></div>):<div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-800/40 text-xs text-emerald-300">Nenhuma conta vencida encontrada.</div>}</div></section>
  </div>
 </div>;
};