import React,{useEffect,useState} from 'react';
import { ShoppingBag, Plus, RefreshCw } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { Product, Supplier } from '../../types';

export const ProductionPurchasesView:React.FC=()=>{
 const [rows,setRows]=useState<any[]>([]);const[products,setProducts]=useState<Product[]>([]);const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[feedback,setFeedback]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[r,p,s]=await Promise.all([productionDb.getPurchases(),productionDb.getProducts(),productionDb.getSuppliers()]);setRows(r);setProducts(p);setSuppliers(s);}catch(e:any){setError(e?.message||'Falha ao carregar compras.');}finally{setBusy(false);}};useEffect(()=>{void load();},[]);
 const create=async()=>{
   const productId=window.prompt('ID do produto a receber:\n'+products.slice(0,20).map(p=>p.name+' = '+p.id).join('\n'))?.trim();if(!productId)return;const product=products.find(p=>p.id===productId);if(!product){setError('Produto não encontrado.');return;}
   const qty=Number((window.prompt('Quantidade:','1')||'0').replace(',','.'));const cost=Number((window.prompt('Custo unitário (R$):',product.costPrice.toFixed(2))||'0').replace(',','.'));if(qty<=0||cost<0){setError('Quantidade/custo inválidos.');return;}
   const supplierId=window.prompt('ID do fornecedor (opcional):\n'+suppliers.slice(0,20).map(s=>s.tradeName+' = '+s.id).join('\n'))?.trim()||'';const invoice=window.prompt('Número da nota (opcional):')?.trim()||'';const term=(window.prompt('Prazo: A_VISTA, 30_DIAS ou PARCELADO','A_VISTA')||'A_VISTA').toUpperCase();
   setBusy(true);setError('');try{await productionDb.confirmPurchase({supplier_id:supplierId||null,invoice_number:invoice,issue_date:new Date().toISOString().slice(0,10),freight:0,discount:0,payment_method:'OUTRO',payment_term:term,due_date:term==='A_VISTA'?null:new Date(Date.now()+30*86400000).toISOString().slice(0,10),items:[{product_id:product.id,quantity:qty,unit_cost:cost}]});setFeedback('Compra confirmada e estoque atualizado em transação única.');await load();}catch(e:any){setError(e?.message||'Não foi possível confirmar a compra.');}finally{setBusy(false);}
 };
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 bg-neutral-950"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-neutral-800"><div><h1 className="text-xl font-black text-white flex items-center gap-2"><ShoppingBag size={22} className="text-amber-400"/>Compras de Produção</h1><p className="text-xs text-neutral-400 mt-1">Entrada de mercadoria, custo, estoque e financeiro em transação atômica.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button><button disabled={busy} onClick={()=>void create()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black flex items-center gap-2"><Plus size={14}/>Registrar compra</button></div></div>
 {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs">{feedback}</div>}
 <div className="bg-neutral-900 border border-neutral-800 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-neutral-950/70 text-neutral-400 uppercase"><tr><th className="p-3 text-left">Data</th><th className="p-3 text-left">Nota</th><th className="p-3 text-left">Prazo</th><th className="p-3 text-right">Total</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y divide-neutral-800">{rows.map(r=><tr key={r.id}><td className="p-3 text-neutral-400">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3 text-white">{r.invoice_number||'—'}</td><td className="p-3 text-neutral-300">{r.payment_term||'—'}</td><td className="p-3 text-right font-mono font-bold text-amber-400">R$ {Number(r.total||0).toFixed(2)}</td><td className="p-3 text-emerald-400">{r.status}</td></tr>)}</tbody></table></div></div>
 </div>;
};