import React,{useEffect,useMemo,useState} from 'react';
import { BarChart3, Boxes, CreditCard, ReceiptText, RefreshCw, TrendingUp } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import { EmptyState, MetricCard, PageHeader, ProductThumb } from '../ui/ProUi';

const money=(v:any)=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});

export const ProductionReportsView:React.FC=()=>{
 const[sales,setSales]=useState<any[]>([]);const[products,setProducts]=useState<any[]>([]);const[finance,setFinance]=useState<any[]>([]);const[analytics,setAnalytics]=useState<any>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[s,p,f,a]=await Promise.all([productionDb.getSales(1000),productionDb.getProducts(),productionDb.getFinancialTransactions(1000),productionDb.getDashboardAnalytics()]);setSales(s);setProducts(p);setFinance(f);setAnalytics(a||{});}catch(e:any){setError(e?.message||'Falha ao carregar relatórios.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const metrics=useMemo(()=>{const paid=sales.filter(s=>s.status==='PAGA');const revenue=paid.reduce((a,s)=>a+Number(s.total||0),0);const costStock=products.reduce((a,p)=>a+Number(p.costPrice||0)*Number(p.currentStock||0),0);const expenses=finance.filter(f=>f.transaction_type==='DESPESA').reduce((a,f)=>a+Number(f.amount||0),0);return{count:paid.length,revenue,ticket:paid.length?revenue/paid.length:0,costStock,expenses};},[sales,products,finance]);
 const top=Array.isArray(analytics?.top_products)?analytics.top_products:[];const categories=Array.isArray(analytics?.top_categories)?analytics.top_categories:[];const payments=Array.isArray(analytics?.payments)?analytics.payments:[];const last7=Array.isArray(analytics?.last7)?analytics.last7:[];const max=Math.max(1,...last7.map((x:any)=>Number(x.revenue||0)));
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
  <PageHeader eyebrow="Inteligência operacional" title="Centro de relatórios" description="Visão consolidada de vendas, estoque, despesas, ticket médio e mix de pagamento." actions={<button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>{busy?'Atualizando...':'Atualizar'}</button>}/>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><MetricCard label="Vendas pagas" value={metrics.count} icon={ReceiptText}/><MetricCard label="Faturamento" value={money(metrics.revenue)} icon={TrendingUp} tone="emerald"/><MetricCard label="Ticket médio" value={money(metrics.ticket)} icon={CreditCard} tone="sky"/><MetricCard label="Custo em estoque" value={money(metrics.costStock)} icon={Boxes} tone="amber"/><MetricCard label="Despesas" value={money(metrics.expenses)} icon={BarChart3} tone="rose"/></div>
  <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-4">
   <section className="ap-panel p-4"><h2 className="font-black">Receita últimos 7 dias</h2>{last7.length?<div className="h-56 mt-6 flex items-end gap-2">{last7.map((x:any)=><div key={x.date} className="flex-1 min-w-0 flex flex-col items-center gap-2 justify-end"><div className="w-full max-w-20 rounded-t-lg bg-gradient-to-t from-amber-700 to-amber-300" style={{height:`${Math.max(3,Number(x.revenue||0)/max*170)}px`}} title={money(x.revenue)}/><span className="text-[9px] text-neutral-500">{new Date(String(x.date)+'T00:00:00').toLocaleDateString('pt-BR',{weekday:'short'})}</span></div>)}</div>:<div className="mt-4"><EmptyState title="Sem dados no período" description="O gráfico será preenchido automaticamente com as vendas pagas."/></div>}</section>
   <section className="ap-panel p-4"><h2 className="font-black">Mix de pagamento</h2><div className="mt-4 space-y-2">{payments.length?payments.map((p:any)=><div key={p.method} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 flex justify-between gap-3"><div><div className="text-xs font-bold">{p.method}</div><div className="text-[9px] text-neutral-500">{p.count} transação(ões)</div></div><div className="font-mono text-xs text-amber-400">{money(p.amount)}</div></div>):<div className="text-xs text-neutral-500">Sem pagamentos para analisar.</div>}</div></section>
  </div>
  <div className="grid xl:grid-cols-[1.15fr_.85fr] gap-4">
   <section className="ap-panel p-4"><div className="flex items-center justify-between"><div><h2 className="font-black">Produtos mais vendidos</h2><p className="text-[10px] text-neutral-500">Ranking por quantidade nos últimos 30 dias</p></div></div><div className="grid sm:grid-cols-2 gap-3 mt-4">{top.length?top.map((tp:any,i:number)=>{const p=products.find(x=>x.id===tp.product_id);return <div key={tp.product_id} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 flex items-center gap-3"><div className="w-7 text-center font-black text-amber-400">#{i+1}</div><ProductThumb src={p?.imageUrl} alt={tp.name}/><div className="min-w-0 flex-1"><div className="text-xs font-bold truncate">{tp.name}</div><div className="text-[10px] text-neutral-500">{Number(tp.quantity||0).toFixed(0)} un.</div><div className="text-[10px] font-mono text-emerald-400">{money(tp.revenue)}</div></div></div>}):<div className="sm:col-span-2"><EmptyState title="Sem ranking de vendas" description="O ranking aparecerá quando houver itens vendidos no período."/></div>}</div></section>
   <section className="ap-panel p-4"><h2 className="font-black">Categorias por faturamento</h2><p className="text-[10px] text-neutral-500">Últimos 30 dias</p><div className="mt-4 space-y-2">{categories.length?categories.map((cat:any,i:number)=><div key={cat.category_id||i} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-xs font-bold truncate">#{i+1} · {cat.name}</div><div className="text-[9px] text-neutral-500">{Number(cat.quantity||0).toFixed(0)} item(ns)</div></div><div className="font-mono text-xs text-amber-400">{money(cat.revenue)}</div></div>):<EmptyState title="Sem categorias no ranking" description="As categorias aparecerão conforme houver vendas pagas."/>}</div></section>
  </div>
 </div>;
};