import React, { useEffect, useState } from 'react';
import { Wallet, Unlock, Lock, ArrowUpRight, ArrowDownLeft, RefreshCw, X, Receipt, TrendingUp, UserRound, Printer, Download, Share2, Pencil, Ban, StickyNote, Bell, Calculator } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import { saveCashClosingReport } from '../../services/cashClosing';
import type { CashRegister, CashSession, CashMovement, User } from '../../types';
import { EmptyState, MetricCard, PageHeader, StatusBadge } from '../ui/ProUi';
import { adegaPrompt } from '../ui/AdegaDialog';

interface Props { currentUser: User; currentSession?: CashSession; onSessionUpdated: () => void | Promise<void>; }

export const ProductionCashView: React.FC<Props> = ({ currentUser, currentSession, onSessionUpdated }) => {
  const [registers,setRegisters]=useState<CashRegister[]>([]); const [sessions,setSessions]=useState<CashSession[]>([]); const [movements,setMovements]=useState<CashMovement[]>([]);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [feedback,setFeedback]=useState('');
  const [selected,setSelected]=useState<any>(null); const [detailBusy,setDetailBusy]=useState(false); const [auditResult,setAuditResult]=useState<any>(null); const [closing,setClosing]=useState<any>(null);
  const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const load=async()=>{try{const[r,s,m]=await Promise.all([productionDb.getCashRegisters(),productionDb.getCashSessions(),currentSession?productionDb.getCashMovements(currentSession.id):Promise.resolve([])]);setRegisters(r);setSessions(s);setMovements(m);}catch(e:any){setError(e?.message||'Falha ao carregar caixa.');}};
  useEffect(()=>{void load();},[currentSession?.id]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setFeedback('');try{await fn();await onSessionUpdated();await load();}catch(e:any){setError(e?.message||'Operação não concluída.');}finally{setBusy(false);}};
  const openSessionDetails=async(session:CashSession)=>{setDetailBusy(true);setError('');setAuditResult(null);try{setSelected(await productionDb.getCashSessionDetails(session.id));}catch(e:any){setError(e?.message||'Não foi possível abrir o histórico deste caixa.');}finally{setDetailBusy(false);}};
  const sessionReportHtml=(d:any)=>`<!doctype html><html><head><meta charset="utf-8"><title>Turno - ${d.session.operatorName}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#111}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.box{border:1px solid #ddd;border-radius:8px;padding:12px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left;font-size:12px}</style></head><body><h1>Histórico do turno · ${d.session.cashRegisterNumber} · ${d.session.operatorName}</h1><p>${new Date(d.session.openedAt).toLocaleString('pt-BR')}</p><div class="grid"><div class="box">Vendas<br><b>${d.metrics.salesCount}</b></div><div class="box">Faturamento<br><b>${money(d.metrics.total)}</b></div><div class="box">Ticket médio<br><b>${money(d.metrics.averageTicket)}</b></div><div class="box">Diferença<br><b>${money(d.session.cashDifference||0)}</b></div></div></body></html>`;
  const printSession=()=>{if(!selected)return;const w=window.open('','_blank','width=900,height=900');if(!w)return setError('Permita pop-ups para imprimir.');w.document.write(sessionReportHtml(selected));w.document.close();w.print();};
  const downloadSession=()=>{if(!selected)return;const blob=new Blob([sessionReportHtml(selected)],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`turno-${selected.session.operatorName}-${selected.session.id}.html`;a.click();URL.revokeObjectURL(url);};
  const shareSession=async()=>{if(!selected)return;const text=`Turno ${selected.session.operatorName} · ${selected.metrics.salesCount} vendas · ${money(selected.metrics.total)}`;if(navigator.share)await navigator.share({title:'Histórico do turno',text});else await navigator.clipboard.writeText(text);};
  const auditSession=async()=>{if(!selected)return;setDetailBusy(true);try{const r=await productionDb.auditCashSession(selected.session.id);setAuditResult(r);}finally{setDetailBusy(false);}};
  const operatorVoucher=async()=>{if(!selected)return;const raw=await adegaPrompt({title:'Vale Operador',label:'Valor do vale (R$)',inputMode:'decimal',confirmLabel:'Continuar'});if(raw===null)return;const amount=Number(raw.replace(',','.'));const reason=(await adegaPrompt({title:'Vale Operador',label:'Motivo obrigatório',confirmLabel:'Registrar vale'}))?.trim();if(!reason||!Number.isFinite(amount)||amount<=0)return;await run(async()=>{await productionDb.registerHrOperatorVoucher(selected.session.operatorId,selected.session.id,amount,reason);});};
  const noteSession=async()=>{if(!selected)return;const note=(await adegaPrompt({title:'Anotação do turno',label:'Anotação',confirmLabel:'Salvar anotação'}))?.trim();if(!note)return;await run(async()=>{await productionDb.addCashSessionAdminNote(selected.session.id,note,confirm('Marcar também como alerta administrativo?'));});};
  const amendSession=async()=>{if(!selected)return;const notes=(await adegaPrompt({title:'Alterar observação administrativa',label:'Observação do turno',defaultValue:selected.session.closureNotes||'',confirmLabel:'Continuar'}))??null;if(notes===null)return;const reason=(await adegaPrompt({title:'Auditoria',label:'Motivo obrigatório da alteração',confirmLabel:'Alterar'}))?.trim();if(!reason)return;await run(async()=>{await productionDb.adminAmendCashSession(selected.session.id,'ALTERAR',notes,reason);setSelected(await productionDb.getCashSessionDetails(selected.session.id));});};
  const cancelSessionRecord=async()=>{if(!selected)return;const reason=(await adegaPrompt({title:'Cancelar registro administrativo',label:'Motivo obrigatório',confirmLabel:'Cancelar registro'}))?.trim();if(!reason)return;await run(async()=>{await productionDb.adminAmendCashSession(selected.session.id,'CANCELAR','',reason);setSelected(await productionDb.getCashSessionDetails(selected.session.id));});};
  const open=()=>void run(async()=>{const occupiedIds=new Set(sessions.filter(s=>s.status==='ABERTO').map(s=>s.cashRegisterId));const free=registers.filter(r=>r.status==='FECHADO'&&!occupiedIds.has(r.id));if(!free.length)throw new Error('Nenhum caixa fechado disponível.');const raw=await adegaPrompt({title:'Abrir caixa',label:'Saldo inicial (R$)',defaultValue:'100',inputMode:'decimal',confirmLabel:'Abrir caixa'});if(raw===null)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<0)throw new Error('Saldo inicial inválido.');await productionDb.openCashSession(free[0].id,currentUser.id,amount);});
  const movement=(type:'SANGRIA'|'SUPRIMENTO')=>void run(async()=>{if(!currentSession)throw new Error('Abra o caixa primeiro.');const raw=await adegaPrompt({title:type==='SANGRIA'?'Registrar sangria':'Registrar suprimento',label:'Valor (R$)',inputMode:'decimal',confirmLabel:'Continuar'});if(!raw)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)throw new Error('Valor inválido.');const reason=(await adegaPrompt({title:type,label:'Motivo da movimentação',confirmLabel:'Registrar'}))?.trim()||'Movimentação operacional';await productionDb.registerCashMovement(currentSession.id,type,amount,reason);});
  const reverseMovement=(m:CashMovement)=>void run(async()=>{const reason=(await adegaPrompt({title:'Estornar '+m.type,label:'Motivo obrigatório do estorno',confirmLabel:'Confirmar estorno'}))?.trim();if(reason)await productionDb.reverseCashMovement(m.id,reason);});
  const askAmount=async(title:string,label:string,def='0')=>{const raw=await adegaPrompt({title,label,defaultValue:def,inputMode:'decimal',confirmLabel:'Continuar'});if(raw===null)return null;const n=Number(raw.replace(',','.'));if(!Number.isFinite(n)||n<0)throw new Error('Valor inválido em '+label+'.');return n;};
  const reconcile=()=>void run(async()=>{if(!currentSession)return;const pix=await askAmount('Relatório de fechamento','PIX confirmado',currentSession.totalPixSales.toFixed(2));if(pix===null)return;const debit=await askAmount('Relatório de fechamento','Débito confirmado',currentSession.totalCardDebitSales.toFixed(2));if(debit===null)return;const credit=await askAmount('Relatório de fechamento','Crédito confirmado',currentSession.totalCardCreditSales.toFixed(2));if(credit===null)return;const cash=await askAmount('Relatório de fechamento','Dinheiro recebido nas vendas',currentSession.totalCashSales.toFixed(2));if(cash===null)return;const r=await saveCashClosingReport(currentSession.id,pix,debit,credit,cash);setClosing(r);setFeedback(`Conferência salva. Saldo da equação: ${money(r.balance)}. Despesas do turno: ${money(r.expenses)}.`);});
  const close=()=>void run(async()=>{if(!currentSession)return;if(!closing)throw new Error('Faça a conferência do relatório antes de fechar o caixa.');const result:any=await productionDb.closeCashSession(currentSession.id,Number(closing.cash_reported||0));setFeedback('Caixa fechado. Diferença: '+money(result?.difference||0));setClosing(null);});

  return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
    <PageHeader eyebrow="Frente de loja" title="Caixa & sessões" description="Vendas, conferência dos recebimentos, sangria e fechamento auditado." actions={<button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs flex gap-2"><RefreshCw size={14}/>Atualizar</button>}/>
    {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs">{feedback}</div>}
    {!currentSession?<EmptyState title={'Nenhuma sessão aberta para '+currentUser.name} description="Abra um caixa para começar." action={<button disabled={busy} onClick={open} className="px-5 py-2.5 rounded-xl bg-amber-500 text-neutral-950 font-black text-xs"><Unlock size={15} className="inline mr-2"/>Abrir caixa</button>}/>:<div className="p-5 rounded-2xl bg-neutral-900 border border-neutral-800 space-y-4">
      <div className="flex justify-between gap-3"><div><div className="font-black">{currentSession.cashRegisterNumber} · ABERTO</div><div className="text-xs text-neutral-500">Operador: {currentSession.operatorName}</div></div><div className="text-right"><div className="text-[10px] text-neutral-500 uppercase">Vendas do turno</div><div className="text-2xl font-black text-amber-400">{money(currentSession.totalSales)}</div></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><MetricCard label="Dinheiro PDV" value={money(currentSession.totalCashSales)} icon={Wallet}/><MetricCard label="PIX PDV" value={money(currentSession.totalPixSales)} icon={ArrowDownLeft} tone="sky"/><MetricCard label="Débito PDV" value={money(currentSession.totalCardDebitSales)} icon={Wallet} tone="violet"/><MetricCard label="Crédito PDV" value={money(currentSession.totalCardCreditSales)} icon={Wallet} tone="violet"/></div>
      {closing&&<div className="p-4 rounded-2xl border border-amber-700/50 bg-amber-950/20"><div className="text-xs font-black text-amber-300 flex gap-2 items-center"><Calculator size={15}/>CONCILIAÇÃO DO FECHAMENTO</div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3 text-xs"><div>Vendas <b>{money(closing.sales)}</b></div><div>PIX <b>- {money(closing.pix)}</b></div><div>Débito <b>- {money(closing.debit)}</b></div><div>Crédito <b>- {money(closing.credit)}</b></div><div>Despesas <b>- {money(closing.expenses)}</b></div><div>Sangria <b>- {money(closing.sangria)}</b></div><div>Dinheiro informado <b>{money(closing.cash_reported)}</b></div><div className={Math.abs(Number(closing.balance||0))<=.01?'text-emerald-300':'text-rose-300'}>Saldo <b>{money(closing.balance)}</b></div></div><div className="text-[10px] text-neutral-500 mt-3">PDV para comparação: PIX {money(closing.pdv_pix)} · Débito {money(closing.pdv_debit)} · Crédito {money(closing.pdv_credit)} · Dinheiro {money(closing.pdv_cash)}</div></div>}
      <div className="flex flex-col sm:flex-row gap-2 pt-3 border-t border-neutral-800"><button disabled={busy} onClick={()=>movement('SANGRIA')} className="px-4 py-2.5 rounded-xl border border-rose-800 text-rose-300 text-xs font-bold"><ArrowUpRight size={15} className="inline mr-2"/>Sangria</button><button disabled={busy} onClick={()=>movement('SUPRIMENTO')} className="px-4 py-2.5 rounded-xl border border-emerald-800 text-emerald-300 text-xs font-bold"><ArrowDownLeft size={15} className="inline mr-2"/>Suprimento</button><button disabled={busy} onClick={reconcile} className="px-4 py-2.5 rounded-xl border border-amber-700 text-amber-300 text-xs font-black"><Calculator size={15} className="inline mr-2"/>Conferir relatório</button><button disabled={busy||!closing} onClick={close} className="sm:ml-auto px-4 py-2.5 rounded-xl bg-rose-600 disabled:opacity-40 text-white text-xs font-black"><Lock size={15} className="inline mr-2"/>Fechar caixa</button></div>
    </div>}
    <div className="grid lg:grid-cols-2 gap-4"><section className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><h2 className="text-sm font-bold mb-3">Movimentações</h2>{movements.length===0?<p className="text-xs text-neutral-500">Nenhuma movimentação.</p>:movements.map(m=><div key={m.id} className="flex justify-between gap-3 text-xs border-b border-neutral-800 py-2"><span>{m.type} · {m.reason}</span><div><b>{money(m.amount)}</b>{!String(m.reason||'').startsWith('ESTORNO:')&&currentSession?.status==='ABERTO'&&<button onClick={()=>reverseMovement(m)} className="ml-2 text-amber-300">ESTORNAR</button>}</div></div>)}</section><section className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><h2 className="text-sm font-bold mb-3">Últimas sessões</h2>{sessions.slice(0,12).map(s=><button key={s.id} onClick={()=>void openSessionDetails(s)} className="w-full flex justify-between text-xs border-b border-neutral-800 py-2 text-left"><span>{s.cashRegisterNumber} · <b className="text-amber-300">{s.operatorName}</b> · {new Date(s.openedAt).toLocaleString('pt-BR')}</span><StatusBadge tone={s.status==='ABERTO'?'success':'neutral'}>{s.status}</StatusBadge></button>)}</section></div>
    {selected&&<div className="fixed inset-0 z-[230] bg-black/80 p-3 sm:p-6 overflow-y-auto"><div className="max-w-5xl mx-auto rounded-3xl border border-neutral-700 bg-neutral-950"><div className="p-5 border-b border-neutral-800"><div className="flex justify-between"><div><div className="text-[10px] text-amber-400 font-black">HISTÓRICO DO TURNO</div><h2 className="text-xl font-black">{selected.session.cashRegisterNumber} · {selected.session.operatorName}</h2></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="flex flex-wrap gap-2 mt-4"><button onClick={()=>void auditSession()} className="px-3 py-2 border border-sky-800 rounded-xl text-xs"><Bell size={14} className="inline mr-1"/>Auditar</button><button onClick={()=>void operatorVoucher()} className="px-3 py-2 border border-amber-700 rounded-xl text-xs"><Wallet size={14} className="inline mr-1"/>Vale</button><button onClick={printSession} className="px-3 py-2 border border-neutral-700 rounded-xl text-xs"><Printer size={14} className="inline mr-1"/>PDF</button><button onClick={downloadSession} className="px-3 py-2 border border-neutral-700 rounded-xl text-xs"><Download size={14} className="inline mr-1"/>Download</button><button onClick={()=>void shareSession()} className="px-3 py-2 border border-neutral-700 rounded-xl text-xs"><Share2 size={14} className="inline mr-1"/>Compartilhar</button><button onClick={()=>void noteSession()} className="px-3 py-2 border border-neutral-700 rounded-xl text-xs"><StickyNote size={14} className="inline mr-1"/>Anotação</button><button onClick={()=>void amendSession()} className="px-3 py-2 border border-neutral-700 rounded-xl text-xs"><Pencil size={14} className="inline mr-1"/>Alterar</button><button onClick={()=>void cancelSessionRecord()} className="px-3 py-2 border border-rose-800 rounded-xl text-xs"><Ban size={14} className="inline mr-1"/>Cancelar</button></div></div><div className="p-5 space-y-4">{auditResult&&<div className="p-4 rounded-2xl border border-sky-800 text-xs">Auditoria: <b>{auditResult.status}</b> · vendas {money(auditResult.sales_total)} · pagamentos {money(auditResult.payments_total)}</div>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MetricCard label="Vendas" value={selected.metrics.salesCount} icon={Receipt}/><MetricCard label="Faturamento" value={money(selected.metrics.total)} icon={TrendingUp}/><MetricCard label="Ticket médio" value={money(selected.metrics.averageTicket)} icon={Wallet}/><MetricCard label="Diferença" value={money(selected.session.cashDifference||0)} icon={UserRound}/></div><section className="p-4 rounded-2xl border border-neutral-800"><h3 className="font-black text-sm">Recebimentos</h3><div className="grid grid-cols-2 gap-2 mt-3">{Object.entries(selected.metrics.paymentTotals||{}).map(([k,v]:any)=><div key={k} className="p-3 bg-neutral-900 rounded-xl"><div className="text-[10px] text-neutral-500">{k}</div><b>{money(v)}</b></div>)}</div></section></div></div></div>}
  </div>;
};
