import React, { useEffect, useState } from 'react';
import { Boxes, RefreshCw, SlidersHorizontal } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { Product } from '../../types';

export const ProductionStockView:React.FC=()=>{
 const [products,setProducts]=useState<Product[]>([]);const[moves,setMoves]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[feedback,setFeedback]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[p,m]=await Promise.all([productionDb.getProducts(),productionDb.getStockMovements()]);setProducts(p);setMoves(m);}catch(e:any){setError(e?.message||'Falha ao carregar estoque.');}finally{setBusy(false);}};useEffect(()=>{void load();},[]);
 const adjust=async(p:Product)=>{const raw=window.prompt('Novo saldo para '+p.name+':',String(p.currentStock));if(raw===null)return;const qty=Number(raw.replace(',','.'));if(!Number.isFinite(qty)||qty<0){setError('Quantidade inválida.');return;}const reason=window.prompt('Motivo do ajuste:')?.trim()||'Ajuste manual';setBusy(true);try{await productionDb.adjustStock(p.id,qty,reason);setFeedback('Estoque ajustado com trilha de auditoria.');await load();}catch(e:any){setError(e?.message||'Falha ao ajustar estoque.');}finally{setBusy(false);}};
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 bg-neutral-950">
  <div className="flex items-start justify-between gap-3 pb-4 border-b border-neutral-800"><div><h1 className="text-xl font-black text-white flex items-center gap-2"><Boxes size={22} className="text-amber-400"/>Estoque de Produção</h1><p className="text-xs text-neutral-400 mt-1">Saldo centralizado e movimentações auditadas no servidor.</p></div><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button></div>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs">{feedback}</div>}
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{products.map(p=><article key={p.id} className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-white">{p.name}</h2><p className="text-[11px] text-neutral-500 mt-1">{p.sku} · mínimo {p.minStock}</p></div><div className={p.currentStock<=p.minStock?'text-rose-400 text-xl font-black':'text-emerald-400 text-xl font-black'}>{p.currentStock}</div></div><button disabled={busy} onClick={()=>void adjust(p)} className="mt-4 w-full px-3 py-2 rounded-xl bg-neutral-800 text-xs font-bold text-neutral-200 flex items-center justify-center gap-2"><SlidersHorizontal size={14}/>Ajustar saldo</button></article>)}</div>
  <section className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><h2 className="font-bold text-white mb-3">Últimas movimentações</h2><div className="space-y-2">{moves.slice(0,50).map(m=><div key={m.id} className="grid grid-cols-[100px_1fr_auto] gap-3 text-xs border-b border-neutral-800 pb-2"><span className="text-amber-400">{m.movement_type}</span><span className="text-neutral-300">{m.reason||'—'}</span><span className="font-mono text-neutral-400">{m.previous_stock} → {m.next_stock}</span></div>)}</div></section>
 </div>;
};