import React,{useEffect,useState} from 'react';
import { ClipboardList, Play, CheckCircle2, RefreshCw } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { Product } from '../../types';

export const ProductionInventoryView:React.FC=()=>{
 const[products,setProducts]=useState<Product[]>([]);const[audits,setAudits]=useState<any[]>([]);const[active,setActive]=useState<string>('');const[counts,setCounts]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[feedback,setFeedback]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[p,a]=await Promise.all([productionDb.getProducts(),productionDb.getInventoryAudits()]);setProducts(p);setAudits(a);const open=a.find((x:any)=>x.status==='EM_ANDAMENTO');setActive(open?.id||'');}catch(e:any){setError(e?.message||'Falha ao carregar inventário.');}finally{setBusy(false);}};useEffect(()=>{void load();},[]);
 const start=async()=>{const notes=window.prompt('Observação do inventário (opcional):')||'';setBusy(true);try{const id=await productionDb.startInventoryAudit(notes);setActive(id);setCounts(Object.fromEntries(products.map(p=>[p.id,String(p.currentStock)])));setFeedback('Inventário iniciado. Informe as contagens físicas.');await load();}catch(e:any){setError(e?.message||'Não foi possível iniciar o inventário.');}finally{setBusy(false);}};
 const finish=async()=>{if(!active)return;const payload=products.map(p=>({product_id:p.id,counted_qty:Number((counts[p.id]??String(p.currentStock)).replace(',','.'))}));if(payload.some(x=>!Number.isFinite(x.counted_qty)||x.counted_qty<0)){setError('Há contagens inválidas.');return;}if(!window.confirm('Finalizar inventário e aplicar divergências ao estoque real?'))return;setBusy(true);try{const r:any=await productionDb.finalizeInventoryAudit(active,payload);setFeedback('Inventário finalizado. Itens alterados: '+Number(r?.changed||0)+'.');setActive('');setCounts({});await load();}catch(e:any){setError(e?.message||'Não foi possível finalizar o inventário.');}finally{setBusy(false);}};
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 bg-neutral-950"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-neutral-800"><div><h1 className="text-xl font-black text-white flex items-center gap-2"><ClipboardList size={22} className="text-amber-400"/>Inventário Físico Produção</h1><p className="text-xs text-neutral-400 mt-1">Divergências são aplicadas em transação auditada no servidor.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button>{!active?<button disabled={busy} onClick={()=>void start()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black flex items-center gap-2"><Play size={14}/>Iniciar</button>:<button disabled={busy} onClick={()=>void finish()} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black flex items-center gap-2"><CheckCircle2 size={14}/>Finalizar</button>}</div></div>
 {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs">{feedback}</div>}
 {active?<div className="bg-neutral-900 border border-neutral-800 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-neutral-950/70 text-neutral-400 uppercase"><tr><th className="p-3 text-left">Produto</th><th className="p-3 text-right">Sistema</th><th className="p-3 text-right">Contagem física</th></tr></thead><tbody className="divide-y divide-neutral-800">{products.map(p=><tr key={p.id}><td className="p-3 text-white">{p.name}</td><td className="p-3 text-right font-mono text-neutral-400">{p.currentStock}</td><td className="p-3 text-right"><input value={counts[p.id]??String(p.currentStock)} onChange={e=>setCounts({...counts,[p.id]:e.target.value})} className="w-24 bg-neutral-950 border border-neutral-700 rounded-lg px-2 py-1.5 text-right font-mono"/></td></tr>)}</tbody></table></div></div>:<div className="p-6 rounded-2xl bg-neutral-900 border border-neutral-800 text-sm text-neutral-400">Nenhum inventário em andamento.</div>}
 <section className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800"><h2 className="font-bold text-white mb-3">Histórico</h2><div className="space-y-2">{audits.map(a=><div key={a.id} className="flex justify-between gap-3 text-xs border-b border-neutral-800 pb-2"><span>{new Date(a.opened_at).toLocaleString('pt-BR')}</span><span className={a.status==='FINALIZADO'?'text-emerald-400':'text-amber-400'}>{a.status}</span></div>)}</div></section>
 </div>;
};