import React,{useEffect,useState} from 'react';
import {Cable,Save,ShieldCheck} from 'lucide-react';
import {platformDb} from '../../services/platformDb';
export const PlatformIntegrationsView:React.FC=()=>{
 const[cfg,setCfg]=useState<any>({provider:'ASAAS',environment:'SANDBOX',api_base_url:'https://api-sandbox.asaas.com/v3',client_id:'',secret_ref:'',webhook_url:'',webhook_secret_ref:'',enabled:false,notes:''});
 const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 useEffect(()=>{platformDb.getPlatformIntegrationSettings().then((x:any[])=>{const a=x.find(v=>v.provider==='ASAAS');if(a)setCfg({...cfg,...a});}).catch((e:any)=>setErr(e?.message||'Falha ao carregar integrações.'));},[]);
 const save=async()=>{setBusy(true);setErr('');setMsg('');try{await platformDb.savePlatformIntegrationSetting(cfg);setMsg('Configuração salva para homologação. Nenhum segredo é armazenado neste formulário: use somente referências de segredo/Vault.');}catch(e:any){setErr(e?.message||'Falha ao salvar.')}finally{setBusy(false)}};
 const field='mt-1 w-full bg-neutral-950 border border-neutral-700 rounded-xl px-3 py-2.5';
 return <div className="space-y-4"><div className="p-4 rounded-2xl border border-emerald-800/40 bg-emerald-950/15 flex gap-3"><ShieldCheck size={18} className="text-emerald-400"/><div><div className="font-black">Integrações da plataforma</div><div className="text-xs text-neutral-500 mt-1">Credenciais administrativas do ATR Control. API Keys e tokens reais devem ficar no backend/Vault; este painel guarda somente referências.</div></div></div>{err&&<div className="p-3 rounded-xl bg-rose-950/40 border border-rose-800 text-xs text-rose-300">{err}</div>}{msg&&<div className="p-3 rounded-xl bg-emerald-950/40 border border-emerald-800 text-xs text-emerald-300">{msg}</div>}<section className="p-5 rounded-2xl bg-neutral-900 border border-neutral-800"><div className="flex gap-2 items-center"><Cable size={18} className="text-amber-400"/><div><h2 className="font-black">Asaas</h2><p className="text-[10px] text-neutral-500">Cobranças, recorrência e webhooks do Adega Pro.</p></div></div><div className="grid md:grid-cols-2 gap-3 mt-4"><label className="text-xs text-neutral-400">Ambiente<select className={field} value={cfg.environment} onChange={e=>setCfg({...cfg,environment:e.target.value,api_base_url:e.target.value==='PRODUCTION'?'https://api.asaas.com/v3':'https://api-sandbox.asaas.com/v3'})}><option value="SANDBOX">Sandbox</option><option value="PRODUCTION">Produção</option></select></label><label className="text-xs text-neutral-400">Base API<input className={field} value={cfg.api_base_url||''} onChange={e=>setCfg({...cfg,api_base_url:e.target.value})}/></label><label className="text-xs text-neutral-400">Referência API Key<input className={field} placeholder="vault://asaas/api-key" value={cfg.secret_ref||''} onChange={e=>setCfg({...cfg,secret_ref:e.target.value})}/></label><label className="text-xs text-neutral-400">URL Webhook<input className={field} placeholder="https://.../webhooks/asaas" value={cfg.webhook_url||''} onChange={e=>setCfg({...cfg,webhook_url:e.target.value})}/></label><label className="text-xs text-neutral-400">Referência authToken do webhook<input className={field} placeholder="vault://asaas/webhook-token" value={cfg.webhook_secret_ref||''} onChange={e=>setCfg({...cfg,webhook_secret_ref:e.target.value})}/></label><label className="text-xs text-neutral-400">Observações<input className={field} value={cfg.notes||''} onChange={e=>setCfg({...cfg,notes:e.target.value})}/></label></div><label className="mt-4 flex items-center gap-2 text-xs"><input type="checkbox" checked={Boolean(cfg.enabled)} onChange={e=>setCfg({...cfg,enabled:e.target.checked})}/>Ativar somente após homologação</label><button disabled={busy} onClick={()=>void save()} className="mt-4 px-5 py-3 rounded-xl bg-amber-500 text-neutral-950 font-black text-sm flex gap-2 items-center"><Save size={15}/>{busy?'Salvando...':'Salvar configuração'}</button></section></div>;
};
