import React, { useEffect, useState } from 'react';
import { platformDb } from '../../services/platformDb';
import { Testimonial, TestimonialsSection } from '../auth/TestimonialsSection';
const empty = {name:'',message:'',photo_url:'',published:false,position:0};
export function TestimonialsControl({onFeedback,onError}:{onFeedback:(v:string)=>void;onError:(v:string)=>void}){
 const [rows,setRows]=useState<Testimonial[]>([]),[form,setForm]=useState<Testimonial>(empty),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);
 const load=async()=>{setBusy(true);try{setRows(await platformDb.getAdminLandingTestimonials());}catch(e:any){onError(e.message||'Falha ao carregar depoimentos.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);onError('');try{await platformDb.saveLandingTestimonial(form);onFeedback(form.published?'Depoimento publicado na landing page.':'Depoimento salvo e oculto na landing page.');setForm({...empty});await load();}catch(e:any){onError(e.message||'Falha ao salvar depoimento.');}finally{setBusy(false);}};
 const upload=async(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>5*1024*1024){onError('Envie uma foto JPG, PNG, WebP ou AVIF de até 5 MB.');return;}setUploading(true);onError('');try{const photo_url=await platformDb.uploadLandingMedia(file);setForm(v=>({...v,photo_url}));onFeedback('Foto enviada. Salve o depoimento para concluir.');}catch(e:any){onError(e.message||'Falha ao enviar foto.');}finally{setUploading(false);}};
 return <div className="space-y-5"><div className="p-5 rounded-2xl border border-amber-500/30 bg-neutral-900"><h2 className="text-xl font-black">Depoimentos de clientes</h2><p className="text-sm text-neutral-400 mt-2">Cadastre, edite e controle quais depoimentos aparecem na landing page. A ordem menor aparece primeiro.</p></div>
 <div className="grid lg:grid-cols-2 gap-5"><form onSubmit={save} className="p-5 rounded-2xl border border-neutral-800 bg-neutral-900 space-y-4"><h3 className="font-black">{form.id?'Editar depoimento':'Novo depoimento'}</h3>
 <label className="block text-sm">Nome do cliente<input required minLength={2} maxLength={120} className="input mt-2" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label>
 <label className="block text-sm">Foto do cliente<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy||uploading} className="block mt-2 w-full text-sm" onChange={e=>void upload(e.target.files?.[0])}/></label><p className="text-xs text-neutral-500">JPG, PNG, WebP ou AVIF, até 5 MB.</p>
 {form.photo_url&&<img src={form.photo_url} alt={`Foto de ${form.name||'cliente'}`} className="w-24 h-24 rounded-full object-cover"/>}
 <label className="block text-sm">Mensagem<textarea required minLength={5} maxLength={1500} rows={5} className="input mt-2" value={form.message} onChange={e=>setForm(v=>({...v,message:e.target.value}))}/></label>
 <label className="block text-sm">Ordem de exibição<input type="number" required min={0} max={999} step={1} className="input mt-2" value={form.position} onChange={e=>setForm(v=>({...v,position:Number(e.target.value)}))}/></label>
 <label className="flex gap-3 items-center text-sm"><input type="checkbox" checked={form.published} onChange={e=>setForm(v=>({...v,published:e.target.checked}))}/>Publicar na landing page</label>
 <div className="flex gap-3"><button disabled={busy||uploading||!form.photo_url} className="btn-primary">{uploading?'Enviando foto...':'Salvar depoimento'}</button><button type="button" disabled={busy||uploading} onClick={()=>setForm({...empty})} className="px-4 py-2 rounded-xl border border-neutral-700">Novo / limpar</button></div>
 </form><section className="p-5 rounded-2xl border border-neutral-800 bg-neutral-900"><div className="flex justify-between items-center"><h3 className="font-black">Cadastrados ({rows.length})</h3><button type="button" disabled={busy} onClick={()=>void load()} className="text-sm text-amber-300">Atualizar</button></div>{rows.length===0&&<p className="text-sm text-neutral-500 mt-4">Cadastre o primeiro depoimento usando o formulário ao lado.</p>}
 <div className="space-y-3 mt-4">{rows.map(row=><article key={row.id} className="p-4 border border-neutral-800 rounded-xl"><div className="flex gap-3 items-center"><img src={row.photo_url} alt={row.name} className="w-12 h-12 rounded-full object-cover"/><div className="min-w-0 flex-1"><h4 className="font-bold break-words">{row.name}</h4><p className="text-xs text-amber-300">{row.published?'Publicado':'Oculto'} · Ordem {row.position}</p></div><button type="button" disabled={busy||uploading} onClick={()=>setForm({...row})} className="text-sm text-amber-300">Editar</button></div><p className="mt-3 text-sm text-neutral-300 whitespace-pre-wrap break-words">{row.message}</p></article>)}</div></section></div>
 {form.photo_url&&form.name&&form.message&&<section className="border border-neutral-800 rounded-2xl"><p className="px-5 pt-4 text-sm text-neutral-500">Prévia do cartão</p><TestimonialsSection items={[form]}/></section>}
 </div>;
}
