import React,{useEffect,useMemo,useState} from 'react';
import { CheckCircle2, Gift, Megaphone, MessageSquare, Plus, RefreshCw, Search, Sparkles, UserRound, Users, WalletCards } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { CashSession, Customer } from '../../types';
import { EmptyState, MetricCard, PageHeader, StatusBadge } from '../ui/ProUi';
import { adegaPrompt } from '../ui/AdegaDialog';

interface Props { currentSession?: CashSession; }
const money=(v:number)=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2});

export const ProductionCustomersView:React.FC<Props>=({currentSession})=>{
 const[customers,setCustomers]=useState<Customer[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[feedback,setFeedback]=useState('');const[search,setSearch]=useState('');const[section,setSection]=useState<'CLIENTES'|'FIADOS'>('CLIENTES');
 const load=async()=>{setBusy(true);setError('');try{setCustomers(await productionDb.getCustomers());}catch(e:any){setError(e?.message||'Falha ao carregar clientes.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const create=async()=>{
  const typeRaw=((await adegaPrompt({title:'Novo cliente',label:'Tipo: MENSAL, FIADO ou AVULSO',defaultValue:'AVULSO',confirmLabel:'Continuar'}))||'AVULSO').toUpperCase();
  if(!['MENSAL','FIADO','AVULSO'].includes(typeRaw)){setError('Tipo de cliente inválido. Use MENSAL, FIADO ou AVULSO.');return;}
  const firstName=(await adegaPrompt({title:'Novo cliente',label:'Nome',confirmLabel:'Continuar'}))?.trim();if(!firstName)return;
  const lastName=(await adegaPrompt({title:'Novo cliente',label:'Sobrenome',confirmLabel:'Continuar'}))?.trim();if(!lastName)return;
  const nickname=(await adegaPrompt({title:'Novo cliente',label:'Apelido (opcional)',confirmLabel:'Continuar'}))?.trim()||'';
  const cpf=(await adegaPrompt({title:'Novo cliente',label:'CPF (opcional)',confirmLabel:'Continuar'}))?.trim()||'';
  const whatsapp=(await adegaPrompt({title:'Novo cliente',label:'WhatsApp *',inputMode:'tel',confirmLabel:'Continuar'}))?.trim();
  if(!whatsapp){setError('WhatsApp é obrigatório para gerar o lead.');return;}
  const email=(await adegaPrompt({title:'Contato do cliente',label:'E-mail (opcional)',inputMode:'email',confirmLabel:'Continuar'}))?.trim()||'';
  const address=(await adegaPrompt({title:'Endereço do cliente',label:'Endereço completo (opcional)',confirmLabel:'Continuar'}))?.trim()||'';
  const notes=(await adegaPrompt({title:'Observações',label:'Observações internas (opcional)',confirmLabel:'Salvar cliente'}))?.trim()||'';
  const name=(firstName+' '+lastName).trim();setBusy(true);setError('');
  try{await productionDb.saveCustomer({name,firstName,lastName,nickname,customerType:typeRaw as 'MENSAL'|'FIADO'|'AVULSO',phone:whatsapp,whatsapp,cpf,email,address,notes,creditLimit:0,status:'LIBERADO'});setFeedback('Cliente salvo e lead registrado.');await load();}
  catch(e:any){setError(e?.message||'Não foi possível salvar cliente.');}finally{setBusy(false);}
 };
 const settle=async(c:Customer)=>{if(c.creditBalance<=0)return;const raw=await adegaPrompt({title:'Receber fiado',message:c.name,label:'Valor recebido (R$)',defaultValue:c.creditBalance.toFixed(2),inputMode:'decimal',confirmLabel:'Continuar'});if(!raw)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return;const method=((await adegaPrompt({title:'Receber fiado',label:'Forma de pagamento: DINHEIRO, PIX, DEBITO ou CREDITO',defaultValue:'DINHEIRO',confirmLabel:'Registrar'}))||'DINHEIRO').toUpperCase();if(!['DINHEIRO','PIX','DEBITO','CREDITO'].includes(method)){setError('Forma de pagamento inválida.');return;}setBusy(true);setError('');try{await productionDb.settleCustomerCredit(c.id,amount,method as any,currentSession?.id);setFeedback('Recebimento registrado com auditoria.');await load();}catch(e:any){setError(e?.message||'Não foi possível registrar o recebimento.');}finally{setBusy(false);}};
 const openWhatsApp=(c:Customer,text:string)=>{const phone=(c.whatsapp||c.phone).replace(/\D/g,'');if(!phone){setError('Cliente sem WhatsApp cadastrado.');return;}window.open('https://api.whatsapp.com/send?phone=55'+phone+'&text='+encodeURIComponent(text),'_blank','noopener,noreferrer');};
 const whatsapp=(c:Customer)=>openWhatsApp(c,'Olá, '+c.name+'! Lembrete de saldo em aberto no valor de R$ '+c.creditBalance.toFixed(2)+'.');
 const promo=async(c:Customer)=>{const offer=(await adegaPrompt({title:'Criar promoção para '+c.name,label:'Oferta / campanha',defaultValue:'Temos uma promoção especial para você hoje!',confirmLabel:'Abrir WhatsApp'}))?.trim();if(!offer)return;openWhatsApp(c,'Olá, '+(c.nickname||c.firstName||c.name)+'! '+offer+' Fale com a gente para aproveitar.');};
 const reactivate=(c:Customer)=>openWhatsApp(c,'Olá, '+(c.nickname||c.firstName||c.name)+'! Faz um tempinho que não vemos você por aqui. Temos novidades e ofertas especiais esperando por você. Quer que eu te mostre?');
 const recommend=async(c:Customer)=>{setBusy(true);setError('');try{const products=(await productionDb.getProducts()).filter(p=>p.status==='ACTIVE'&&p.currentStock>0&&p.salePrice>0).sort((a,b)=>b.currentStock-a.currentStock).slice(0,3);if(!products.length){setError('Não há produtos com estoque disponível para recomendar.');return;}const list=products.map(p=>p.name+' por '+money(p.salePrice)).join(', ');openWhatsApp(c,'Olá, '+(c.nickname||c.firstName||c.name)+'! Separei algumas opções que podem te interessar: '+list+'. Quer que eu reserve algum para você?');}catch(e:any){setError(e?.message||'Não foi possível gerar recomendações.');}finally{setBusy(false);}};
 const filtered=useMemo(()=>{const base=section==='FIADOS'?customers.filter(c=>c.customerType==='FIADO'||c.creditBalance>0):customers;const q=search.trim().toLowerCase();if(!q)return base;return base.filter(c=>[c.name,c.firstName,c.lastName,c.nickname,c.whatsapp,c.phone,c.cpf,c.customerType].some(v=>String(v||'').toLowerCase().includes(q)));},[customers,search,section]);
 const debt=customers.reduce((s,c)=>s+c.creditBalance,0);const blocked=customers.filter(c=>c.status==='BLOQUEADO').length;const purchases=customers.reduce((s,c)=>s+c.totalPurchases,0);

 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
  <PageHeader eyebrow="Relacionamento" title="Clientes & Fiados" description="Cadastro de clientes e controle de fiados separados na mesma área." actions={<><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button><button disabled={busy} onClick={()=>void create()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black flex items-center gap-2"><Plus size={15}/>Cadastrar cliente</button></>}/>
  <div className="inline-flex p-1 rounded-xl bg-neutral-900 border border-neutral-800 gap-1"><button onClick={()=>setSection('CLIENTES')} className={'px-4 py-2 rounded-lg text-xs font-black '+(section==='CLIENTES'?'bg-amber-500 text-neutral-950':'text-neutral-400 hover:text-white')}>Clientes</button><button onClick={()=>setSection('FIADOS')} className={'px-4 py-2 rounded-lg text-xs font-black '+(section==='FIADOS'?'bg-amber-500 text-neutral-950':'text-neutral-400 hover:text-white')}>Fiados</button></div>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs flex items-center gap-2"><CheckCircle2 size={14}/>{feedback}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MetricCard label={section==='FIADOS'?'Clientes fiado':'Clientes'} value={section==='FIADOS'?customers.filter(c=>c.customerType==='FIADO'||c.creditBalance>0).length:customers.length} icon={Users}/><MetricCard label="Fiado em aberto" value={money(debt)} icon={WalletCards} tone={debt>0?'rose':'emerald'}/><MetricCard label="Bloqueados" value={blocked} icon={UserRound} tone={blocked?'rose':'emerald'}/><MetricCard label="Compras acumuladas" value={money(purchases)} icon={WalletCards} tone="amber"/></div>
  <div className="relative max-w-xl"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, apelido, WhatsApp, CPF ou tipo..." className="w-full rounded-xl bg-neutral-900 border border-neutral-800 pl-9 pr-3 py-2.5 text-xs outline-none focus:border-amber-500"/></div>
  {filtered.length===0?<EmptyState title="Nenhum cliente encontrado" description="Cadastre o primeiro cliente ou ajuste a busca." action={<button onClick={()=>void create()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black">Cadastrar cliente</button>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map(c=><article key={c.id} className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800 hover:border-amber-500/30"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black text-white truncate">{c.name}</div><div className="text-[10px] text-neutral-500 mt-1">{c.nickname?c.nickname+' · ':''}{c.whatsapp||c.phone||'Sem WhatsApp'}{c.cpf?' · CPF '+c.cpf:''}</div></div><div className="flex flex-col items-end gap-1"><StatusBadge tone="neutral">{c.customerType||'AVULSO'}</StatusBadge><StatusBadge tone={c.status==='BLOQUEADO'?'danger':'success'}>{c.status||'LIBERADO'}</StatusBadge></div></div><div className="grid grid-cols-2 gap-2 mt-4"><div className="p-3 rounded-xl bg-neutral-950 border border-neutral-800"><div className="text-[9px] text-neutral-500">Limite</div><div className="mt-1 font-mono font-black">{money(c.creditLimit)}</div></div><div className="p-3 rounded-xl bg-neutral-950 border border-neutral-800"><div className="text-[9px] text-neutral-500">Saldo fiado</div><div className={'mt-1 font-mono font-black '+(c.creditBalance>0?'text-rose-400':'text-emerald-400')}>{money(c.creditBalance)}</div></div></div><div className="mt-3 text-[10px] text-neutral-500">Compras: {money(c.totalPurchases)}{c.lastPurchaseDate?' · última '+new Date(c.lastPurchaseDate).toLocaleDateString('pt-BR'):''}</div><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={()=>void promo(c)} className="px-3 py-2 rounded-xl bg-violet-950/40 border border-violet-800 text-violet-300 text-xs font-bold flex items-center justify-center gap-2"><Megaphone size={14}/>Promoção</button><button onClick={()=>void recommend(c)} className="px-3 py-2 rounded-xl bg-sky-950/40 border border-sky-800 text-sky-300 text-xs font-bold flex items-center justify-center gap-2"><Sparkles size={14}/>Recomendar</button><button onClick={()=>reactivate(c)} className="px-3 py-2 rounded-xl bg-emerald-950 border border-emerald-800 text-emerald-300 text-xs font-bold flex items-center justify-center gap-2"><Gift size={14}/>Reativar</button>{c.creditBalance>0?<button disabled={busy} onClick={()=>void settle(c)} className="px-3 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black">Receber</button>:<button onClick={()=>openWhatsApp(c,'Olá, '+c.name+'! Tudo bem?')} className="px-3 py-2 rounded-xl bg-neutral-950 border border-neutral-800 text-neutral-300 text-xs font-bold flex items-center justify-center gap-2"><MessageSquare size={14}/>WhatsApp</button>}</div></article>)}</div>}
 </div>;
};
