import React,{useEffect,useMemo,useState} from 'react';
import { CheckCircle2, MessageSquare, Plus, RefreshCw, Search, UserRound, Users, WalletCards } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import type { CashSession, Customer } from '../../types';
import { EmptyState, MetricCard, PageHeader, StatusBadge } from '../ui/ProUi';

interface Props { currentSession?: CashSession; }
const money=(v:number)=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2});

export const ProductionCustomersView:React.FC<Props>=({currentSession})=>{
 const[customers,setCustomers]=useState<Customer[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[feedback,setFeedback]=useState('');const[search,setSearch]=useState('');
 const load=async()=>{setBusy(true);setError('');try{setCustomers(await productionDb.getCustomers());}catch(e:any){setError(e?.message||'Falha ao carregar clientes.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const create=async()=>{const name=window.prompt('Nome completo do cliente:')?.trim();if(!name)return;const phone=window.prompt('WhatsApp / telefone:')?.trim();if(!phone)return;const cpf=window.prompt('CPF (opcional):')?.trim()||'';const limitRaw=window.prompt('Limite de fiado (R$):','300')||'0';const creditLimit=Number(limitRaw.replace(',','.'))||0;setBusy(true);setError('');try{await productionDb.saveCustomer({name,phone,cpf,creditLimit,status:'LIBERADO'});setFeedback('Cliente salvo em produção.');await load();}catch(e:any){setError(e?.message||'Não foi possível salvar cliente.');}finally{setBusy(false);}};
 const settle=async(c:Customer)=>{if(c.creditBalance<=0)return;const raw=window.prompt('Valor recebido de '+c.name+' (R$):',c.creditBalance.toFixed(2));if(!raw)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return;const method=(window.prompt('Forma: DINHEIRO, PIX, DEBITO ou CREDITO','DINHEIRO')||'DINHEIRO').toUpperCase();if(!['DINHEIRO','PIX','DEBITO','CREDITO'].includes(method)){setError('Forma de pagamento inválida.');return;}setBusy(true);setError('');try{await productionDb.settleCustomerCredit(c.id,amount,method as any,currentSession?.id);setFeedback('Recebimento registrado com auditoria.');await load();}catch(e:any){setError(e?.message||'Não foi possível registrar o recebimento.');}finally{setBusy(false);}};
 const whatsapp=(c:Customer)=>{const phone=c.phone.replace(/\D/g,'');const text=encodeURIComponent('Olá, '+c.name+'! Lembrete de saldo em aberto no valor de R$ '+c.creditBalance.toFixed(2)+'.');window.open('https://api.whatsapp.com/send?phone=55'+phone+'&text='+text,'_blank','noopener,noreferrer');};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return customers;return customers.filter(c=>[c.name,c.phone,c.cpf,c.email].some(v=>String(v||'').toLowerCase().includes(q)));},[customers,search]);
 const debt=customers.reduce((s,c)=>s+c.creditBalance,0);const blocked=customers.filter(c=>c.status==='BLOQUEADO').length;const purchases=customers.reduce((s,c)=>s+c.totalPurchases,0);

 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5">
  <PageHeader eyebrow="Relacionamento" title="Clientes & fiado" description="Cadastro, histórico comercial, limite e recebimentos vinculados à loja ativa." actions={<><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button><button disabled={busy} onClick={()=>void create()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black flex items-center gap-2"><Plus size={15}/>Cadastrar cliente</button></>}/>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}{feedback&&<div className="p-3 rounded-xl border border-emerald-800 bg-emerald-950/40 text-emerald-300 text-xs flex items-center gap-2"><CheckCircle2 size={14}/>{feedback}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MetricCard label="Clientes" value={customers.length} icon={Users}/><MetricCard label="Fiado em aberto" value={money(debt)} icon={WalletCards} tone={debt>0?'rose':'emerald'}/><MetricCard label="Bloqueados" value={blocked} icon={UserRound} tone={blocked?'rose':'emerald'}/><MetricCard label="Compras acumuladas" value={money(purchases)} icon={WalletCards} tone="amber"/></div>
  <div className="relative max-w-xl"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente por nome, telefone, CPF ou e-mail..." className="w-full rounded-xl bg-neutral-900 border border-neutral-800 pl-9 pr-3 py-2.5 text-xs outline-none focus:border-amber-500"/></div>
  {filtered.length===0?<EmptyState title="Nenhum cliente encontrado" description="Cadastre o primeiro cliente ou ajuste a busca." action={<button onClick={()=>void create()} className="px-4 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black">Cadastrar cliente</button>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map(c=><article key={c.id} className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800 hover:border-amber-500/30"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black text-white truncate">{c.name}</div><div className="text-[10px] text-neutral-500 mt-1">{c.phone||'Sem telefone'}{c.cpf?' · CPF '+c.cpf:''}</div></div><StatusBadge tone={c.status==='BLOQUEADO'?'danger':'success'}>{c.status||'LIBERADO'}</StatusBadge></div><div className="grid grid-cols-2 gap-2 mt-4"><div className="p-3 rounded-xl bg-neutral-950 border border-neutral-800"><div className="text-[9px] text-neutral-500">Limite</div><div className="mt-1 font-mono font-black">{money(c.creditLimit)}</div></div><div className="p-3 rounded-xl bg-neutral-950 border border-neutral-800"><div className="text-[9px] text-neutral-500">Saldo fiado</div><div className={'mt-1 font-mono font-black '+(c.creditBalance>0?'text-rose-400':'text-emerald-400')}>{money(c.creditBalance)}</div></div></div><div className="mt-3 text-[10px] text-neutral-500">Compras: {money(c.totalPurchases)}{c.lastPurchaseDate?' · última '+new Date(c.lastPurchaseDate).toLocaleDateString('pt-BR'):''}</div>{c.creditBalance>0&&<div className="flex gap-2 mt-4"><button onClick={()=>whatsapp(c)} className="flex-1 px-3 py-2 rounded-xl bg-emerald-950 border border-emerald-800 text-emerald-300 text-xs font-bold flex items-center justify-center gap-2"><MessageSquare size={14}/>WhatsApp</button><button disabled={busy} onClick={()=>void settle(c)} className="flex-1 px-3 py-2 rounded-xl bg-amber-500 text-neutral-950 text-xs font-black">Receber</button></div>}</article>)}</div>}
 </div>;
};