export const APP_RELEASE = {
  releaseId: '2026-09-30-2353-v5.2',
  version: '5.2',
  dateLabel: '30/09/2026 · 23:53',
  title: 'Adega Pro atualizado',
  subtitle: 'Novidades desta versão',
  notes: [
    'Cadastro de clientes simplificado com Mensal/Avulso e WhatsApp obrigatório.',
    'Categorias e fornecedores sincronizados para o ambiente do cliente.',
    'Importação de produtos da planilha e catálogo demonstração com estoque inicial.',
    'Janelas nativas do navegador substituídas por modais próprios do Adega Pro.',
    'Ajustes de catálogo, estoque e compatibilidade do PDV.',
    'Área Clientes & Fiados separada em abas e novo tipo de cliente FIADO.',
    'Novo programa de indicação na landing page com benefícios comerciais para clientes ativos.',
    'Política de indicação e comissionamento comercial detalhada nos termos do Adega Pro.',
    'PDV passa a abrir para consulta mesmo sem caixa, Mini PDV permanece ativo e a busca foi sincronizada globalmente.',
    'ATR Control Premium agora controla módulos por cliente, do básico ao avançado.',
    'Suporte ganhou backup geral JSON com download e importação validada.',
    'Lojas & Unidades ganhou troca segura de unidade; Configurações concentra impressão e teste de cupom.',
    'Modo demonstração foi reduzido e as políticas completas ficaram protegidas por contratação.',
    'Termos r5 incluem guia prático de uso seguro do Adega Pro.',
    'Ações comerciais nos clientes: promoção, reativação, recomendação de produtos e WhatsApp.',
    'Tema Claro/Escuro disponível no cabeçalho e em Configurações, mantendo responsividade.',
    'Auditoria ganhou diagnóstico automático de sinais de erro e recorrência.',
    'Landing destaca IA e automação inteligente para marketing, recomendações na venda e auditoria assistida.',
    'Políticas r6 detalham uso de IA, possibilidade de erros, conferência humana e responsabilidades de serviços de terceiros.',
    'Segurança multi-tenant reforçada: isolamento tenant/loja obrigatório, bloqueio de escalada de privilégio e RPCs anônimas fechadas.',
    'ATR Control ganhou Vendedores parceiros, links individuais de indicação, funil comercial, comissões e repasses.',
    'Controle de proteção avançada de dados por cliente com estados BLOQUEADA, DISPONÍVEL e MIGRAÇÃO.',
    'Dashboard administrativo ampliado com gráficos, distribuição operacional e central de prioridades.',
    'Política comercial dos autônomos fechada: R$ 35 na assinatura e R$ 200 no personalizado, somente após pagamento confirmado.',
    'Repasse por vendedor pode ser imediato ou acumulado para fechamento mensal, com validação e histórico no ATR Control.',
    'Supabase endurecido: privilégios anônimos reduzidos, TRUNCATE removido, defaults fechados e tabelas administrativas em modo RPC-only.',
    'RLS corrigido em acesso a lojas e financeiro; auditoria futura deixa de duplicar campos sensíveis de clientes.',
    'ATR Control ganhou gestão independente de indicações de clientes, fidelidade, descontos, pontos e cashback.',
    'Central de notificações, CTAs de demonstração e políticas de fidelidade atualizados.'
  ]
} as const;

export const APP_VERSION_LABEL = `v${APP_RELEASE.version} · ${APP_RELEASE.dateLabel}`;
