export const APP_RELEASE = {
  releaseId: '2026-10-04-cash-reconciliation-v5.29',
  version: '5.29',
  dateLabel: '04/10/2026 · 17:25 BRT',
  title: 'Conciliação correta do fechamento de caixa',
  subtitle: 'Novidades desta versão',
  notes: [
    'Caixa: diferença de fechamento agora compara dinheiro contado com o valor físico esperado, considerando saldo inicial, vendas em dinheiro, suprimentos, sangrias e despesas; elimina falso rombo causado pela fórmula anterior.',
    'Desktop 1.1.5: após a abertura com a marca oficial, o aplicativo inicia em Login/Cadastro da empresa; o PIN aparece somente depois da autenticação principal.',
    'Abertura Windows: a tela oficial do ADEGA PRO permanece visível por tempo mínimo para evitar que o aplicativo pareça abrir diretamente no bloqueio do operador.',
    'Desktop 1.1.4: nova tela de abertura com a marca oficial do ADEGA PRO enquanto a interface principal é preparada.',
    'Arquivo Windows: versão, produto, fabricante, descrição e copyright passam a ser validados automaticamente no build.',
    'Desktop 1.1.3: inicia somente com a interface gráfica do ADEGA PRO, sem abrir a janela CMD em segundo plano.',
    'Desktop 1.1.2: sincroniza a versão Windows com as correções publicadas no sistema online.',
    'Acesso: o link de recuperação agora abre uma tela segura para definir e confirmar a nova senha antes de entrar no sistema.',
    'Clientes: e-mail, endereço e observações passam a ser coletados e persistidos sem serem apagados em atualizações.',
    'Segurança web: adicionados cabeçalhos contra framing, interpretação incorreta de conteúdo e vazamento de referência.',
    'Jurídico: os hashes SHA-256 da versão r8 foram reconciliados com o conteúdo canônico efetivamente publicado.',
    'Desktop 1.1.1: corrige a tela branca ao abrir módulos pelo menu Janelas e evita bloqueio do WebView2 no Windows.',
    'Desktop: Dashboard, PDV, Vendas, Caixa, Produtos, Estoque, Financeiro, Clientes e Relatórios agora podem ser abertos em janelas independentes pelo menu Janelas.',
    'PDV: nova Tela do Cliente para segundo monitor, sincronizada em tempo real apenas com itens, quantidades e totais da venda ativa, sem dados pessoais do cliente.',
    'Jurídico: os seis documentos obrigatórios r8 agora possuem SHA-256 reproduzível calculado sobre payload canônico; teste automático impede divergência silenciosa entre texto publicado e hash registrado.',
    'Inventário: novas contagens físicas ficam vinculadas automaticamente ao caixa/turno aberto do operador; inventários anteriores permanecem compatíveis e nenhum saldo existente é alterado.',
    'Cashback: estorno, cancelamento ou chargeback devolve pontos e saldo, mas não reabre a cota de indicação do mesmo mês-calendário; regra alinhada ao índice único e ao ledger idempotente.',
    'Landing page: nova Política de Fidelidade e Indicações, separada do programa de vendedores, com Plano Mensal de R$ 149 e Fidelização + Personalização de R$ 990 em até 3x ou R$ 800 à vista.',
    'Fidelização: quatro meses sem mensalidade; a partir do 5º mês, mensalidade de R$ 149 e uma indicação válida convertida no mês reduz a mensalidade seguinte para R$ 75, sem acumular cota.',
    'Caixas & Sessões: histórico clicável por turno com mini-dashboard do operador, vendas, faturamento, pagamentos, sangrias, suprimentos e diferença de fechamento.',
    'Ajuda: nova seção Como usar o Adega Pro disponível aos usuários logados pela Central de Suporte.',
    'Landing page: novas áreas de Novidades & Updates e FAQ robusto sobre operação, multi-loja, estoque, caixa, segurança e suporte.',
    'Release: corrige o metadado do rodapé para registrar a data e hora reais desta publicação.',
    'Estoque: validade por lote, FEFO, alertas de vencimento, ranking de giro, estoque estacionado e sugestão de reposição.',
    'Dashboard: reposição sugerida, maior saída, estoque estacionado e alertas de validade da loja ativa.',
    'RH: entrada por PIN, saída automática no fechamento do turno e registro administrativo de faltas com data, hora e observação.',
    'Compras: lista imprimível de reposição para apoiar a próxima compra sem gerar pedido automático.',
    'Mini PDV: novo modo de tela cheia com restauração rápida; ESC/fechar ficam protegidos quando existe venda em andamento e orientam finalizar ou cancelar antes de sair.',
    'Operação 24h: Mini PDV e PDV completo permanecem sincronizados por loja; PIN aceita teclado físico; dashboard mostra faturamento do dia e por turno; caixa ganhou estorno auditável de sangria/suprimento.',
    'Mini PDV: carregamento de produtos, estoque, vendas, clientes e caixa ficou resiliente a falhas isoladas de sincronização, preservando os dados já disponíveis para o vendedor.',
    'Vendas & cupons: nova tela de alteração permite corrigir a forma de pagamento registrada (Dinheiro, PIX, Débito, Crédito, Voucher ou Fiado) com sincronização do caixa.',
    'Vendas & cupons: ações administrativas para visualizar cupom, alterar desconto e cancelar venda com estorno sincronizado de estoque, caixa e financeiro.',
    'Indicações: clientes ativos agora podem indicar novos clientes pelo Adega Pro, acompanhar status, pontos e cashback com sincronização direta ao ATR Control.',
    'PDV: pagamento em Cartão agora abre a escolha entre Débito e Crédito antes da finalização da venda.',
    'PIX manual por loja: QR Code configurado em Integrações e confirmação Pendente, Cancelado ou Pago antes de finalizar a venda.',
    'PDV e estoque: operações reforçadas por loja para manter vendas, caixa e saldo de estoque sincronizados na unidade ativa.',
    'Caixa: abertura, movimentações e fechamento permanecem vinculados à loja e ao operador responsável.',
    'Clientes & Fiados: cadastro e controle operacional continuam separados e vinculados ao ambiente da loja.',
    'Central de notificações do sistema reúne avisos operacionais do Adega Pro, incluindo estoque, validade e pendências de RH.',
    'Categorias, fornecedores, produtos e catálogo permanecem sincronizados com o ambiente operacional do cliente.',
    'Configurações e impressão concentram preferências de cupom, impressora e operação da loja.'
  ]} as const;

export const APP_VERSION_LABEL = `v${APP_RELEASE.version} · ${APP_RELEASE.dateLabel}`;
