import React, { useEffect, useState } from 'react';
import { Boxes, Users, Wallet, ShoppingCart, RefreshCw, Database, CalendarClock } from 'lucide-react';
import { productionDb } from '../../services/productionDb';

export const ProductionDashboardView:React.FC<{onNavigate:(tab:string)=>void}> = ({onNavigate}) => {
  const [stats,setStats]=useState({products:0,low:0,customers:0,openCash:0,expiry:0}); const [busy,setBusy]=useState(true); const [error,setError]=useState(''); const [expiryAlerts,setExpiryAlerts]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]);
  const load=async()=>{setBusy(true);setError('');try{const [p,c,s,a]=await Promise.all([productionDb.getProducts(),productionDb.getCustomers(),productionDb.getCashSessions(),productionDb.getExpiryAlerts(30)]);setProducts(p);setExpiryAlerts(a);setStats({products:p.length,low:p.filter(x=>!x.isCombo&&x.currentStock<=x.minStock).length,customers:c.length,openCash:s.filter(x=>x.status==='ABERTO').length,expiry:a.length});}catch(e:any){setError(e?.message||'Falha ao carregar dashboard.');}finally{setBusy(false);}};
  useEffect(()=>{void load();},[]);
  const cards=[{label:'Produtos',value:stats.products,icon:Boxes,tab:'products'},{label:'Estoque baixo',value:stats.low,icon:ShoppingCart,tab:'stock'},{label:'Validade ≤ 30 dias',value:stats.expiry,icon:CalendarClock,tab:'purchases'},{label:'Clientes',value:stats.customers,icon:Users,tab:'customers'},{label:'Caixas abertos',value:stats.openCash,icon:Wallet,tab:'cash'}];
  return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 bg-neutral-950">
    <div className="flex items-start justify-between gap-4 pb-4 border-b border-neutral-800"><div><h1 className="text-xl font-black text-white flex items-center gap-2"><Database size={22} className="text-emerald-400"/>Dashboard Produção</h1><p className="text-xs text-neutral-400 mt-1">Indicadores carregados exclusivamente do Supabase.</p></div><button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button></div>
    {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}
    <div className="grid grid-cols-1 min-[420px]:grid-cols-2 lg:grid-cols-5 gap-3">{cards.map(({label,value,icon:Icon,tab})=><button key={label} onClick={()=>onNavigate(tab)} className="group text-left p-5 rounded-2xl bg-gradient-to-b from-neutral-900 to-[#0d0d0d] border border-neutral-800 hover:border-amber-500/40 transition-all"><div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/20 grid place-items-center mb-4"><Icon size={17} className="text-amber-400"/></div><div className="text-3xl font-black text-white">{busy?'—':value}</div><div className="text-xs text-neutral-500 mt-1 group-hover:text-neutral-300">{label}</div></button>)}</div>
    <div className="grid xl:grid-cols-[1.3fr_.7fr] gap-4">
      <section className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800">
        <div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-sm text-white">Catálogo da operação</h2><p className="text-[10px] text-neutral-500 mt-1">Produtos com foto, preço e estoque sincronizados.</p></div><button onClick={()=>onNavigate('products')} className="text-[10px] text-amber-400 font-black">VER CATÁLOGO</button></div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4">{products.slice(0,4).map((p:any)=><button key={p.id} onClick={()=>onNavigate('products')} className="text-left rounded-xl bg-neutral-950 border border-neutral-800 overflow-hidden"><div className="aspect-[4/3] bg-black">{p.imageUrl?<img src={p.imageUrl} alt={p.name} className="w-full h-full object-contain p-2"/>:<div className="w-full h-full grid place-items-center"><Boxes size={24} className="text-neutral-700"/></div>}</div><div className="p-2"><div className="text-[10px] font-bold text-white truncate">{p.name}</div><div className="mt-1 flex justify-between gap-2"><span className="font-mono text-[10px] text-amber-400">R$ {Number(p.salePrice||0).toFixed(2)}</span><span className="text-[9px] text-neutral-600">{p.currentStock} {p.unit}</span></div></div></button>)}</div>
      </section>
      <section className="space-y-3">
        {expiryAlerts.length>0?<button onClick={()=>onNavigate('purchases')} className="w-full text-left p-4 rounded-2xl bg-amber-950/20 border border-amber-800/50 text-sm text-neutral-300"><div className="font-black text-amber-300 flex items-center gap-2"><CalendarClock size={16}/>Atenção a vencimentos</div><div className="text-xs text-neutral-400 mt-1">{expiryAlerts.length} lote(s) vencido(s) ou com vencimento nos próximos 30 dias.</div></button>:<div className="p-4 rounded-2xl bg-emerald-950/20 border border-emerald-800/40"><div className="text-sm font-black text-emerald-300">Validades sob controle</div><div className="text-xs text-neutral-500 mt-1">Nenhum alerta de validade nos próximos 30 dias.</div></div>}
        <div className="p-4 rounded-2xl bg-neutral-900 border border-neutral-800 text-xs text-neutral-400">Ambiente real conectado ao banco de produção com isolamento por tenant, operador seguro e trilha de auditoria.</div>
      </section>
    </div>
  </div>;
};