CREATE OR REPLACE FUNCTION public.close_cash_session_secure(p_cash_session_id uuid, p_operator_token text, p_counted_cash numeric, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'private', 'auth'
AS $function$
declare s public.cash_sessions%rowtype; op uuid; expected numeric; counted numeric; diff numeric; nm text; immediate numeric; fiado numeric; settled numeric;
begin if auth.uid() is null then raise exception 'authentication required'; end if; select * into s from public.cash_sessions where id=p_cash_session_id for update; if not found or s.status<>'ABERTO' then raise exception 'cash session is not open'; end if; if not private.has_store_access(s.store_id) then raise exception 'forbidden'; end if; op:=private.require_operator_session(s.store_id,p_operator_token); if not exists(select 1 from public.operator_sessions os where os.store_id=s.store_id and os.operator_id=op and os.auth_user_id=auth.uid() and os.token_hash=encode(extensions.digest(p_operator_token,'sha256'),'hex') and os.revoked_at is null and os.expires_at>now() and os.created_at>=now()-interval '5 minutes') then raise exception 'Confirme o PIN do operador antes do fechamento definitivo'; end if; if s.operator_ref is distinct from op then raise exception 'operator does not own cash session'; end if; if not private.operator_can(op,'cash.close') or not private.has_feature(s.tenant_id,'cash.close','USE') then raise exception 'operator cannot close cash'; end if; if s.closing_report_at is null then raise exception 'closing reconciliation required'; end if;
immediate:=round(coalesce(s.closing_report_pix,0)+coalesce(s.closing_report_debit,0)+coalesce(s.closing_report_credit,0)+coalesce(s.closing_report_cash,0),2); fiado:=private.cash_session_fiado_total(s.id); settled:=round(immediate+fiado,2); if abs(settled-round(coalesce(s.total_sales,0),2))>.01 then raise exception 'closing reconciliation is no longer valid'; end if; counted:=p_counted_cash; if counted is null or counted<0 then raise exception 'invalid counted cash'; end if; expected:=round(coalesce(s.initial_balance,0)+coalesce(s.closing_report_cash,0)+coalesce(s.total_supplies,0)-coalesce(s.total_withdrawals,0)-coalesce(s.total_expenses,0),2); diff:=round(counted-expected,2);
update public.cash_sessions set closing_report_fiado=fiado,expected_cash=expected,counted_cash=counted,cash_difference=diff,closure_notes=nullif(trim(coalesce(p_notes,'')),''),status='FECHADO',closed_at=now() where id=s.id; update public.cash_registers set status='FECHADO' where id=s.cash_register_id; select name into nm from public.operators where id=op; insert into public.hr_shift_attendance(tenant_id,store_id,operator_id,operator_name,event_type,event_at,notes,access_origin) values(s.tenant_id,s.store_id,op,coalesce(nm,'Operador'),'SAIDA_TURNO',now(),coalesce(nullif(trim(coalesce(p_notes,'')),''),'Saída automática vinculada ao turno de caixa '||s.id::text),'NA_LOJA');
return jsonb_build_object('session_id',s.id,'immediate_receipts',immediate,'fiado_receivable',fiado,'reconciliation_difference',round(settled-coalesce(s.total_sales,0),2),'expected_physical_cash',expected,'counted_cash',counted,'physical_cash_difference',diff); end $function$
