
create table if not exists public.auth_rate_limit_events (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('login','signup','recovery')),
  identifier_hash text not null,
  user_agent_hash text,
  created_at timestamptz not null default now()
);

alter table public.auth_rate_limit_events enable row level security;
revoke all on public.auth_rate_limit_events from anon, authenticated;

create index if not exists idx_auth_rate_limit_lookup
  on public.auth_rate_limit_events(action, identifier_hash, created_at desc);

create or replace function public.check_auth_rate_limit(
  p_action text,
  p_identifier text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_action text := lower(trim(p_action));
  v_identifier_hash text;
  v_user_agent_hash text;
  v_window interval;
  v_limit integer;
  v_count integer;
  v_oldest timestamptz;
  v_retry integer;
begin
  if v_action not in ('login','signup','recovery') then
    raise exception 'invalid action';
  end if;

  if p_identifier is null or length(trim(p_identifier)) < 3 then
    raise exception 'invalid identifier';
  end if;

  v_identifier_hash := encode(digest(lower(trim(p_identifier)), 'sha256'), 'hex');
  v_user_agent_hash := case
    when p_user_agent is null then null
    else encode(digest(p_user_agent, 'sha256'), 'hex')
  end;

  if v_action = 'login' then
    v_window := interval '15 minutes';
    v_limit := 8;
  elsif v_action = 'signup' then
    v_window := interval '60 minutes';
    v_limit := 3;
  else
    v_window := interval '60 minutes';
    v_limit := 3;
  end if;

  select count(*), min(created_at)
    into v_count, v_oldest
  from public.auth_rate_limit_events
  where action = v_action
    and identifier_hash = v_identifier_hash
    and created_at >= now() - v_window;

  if v_count >= v_limit then
    v_retry := greatest(
      1,
      ceil(extract(epoch from ((v_oldest + v_window) - now())))::integer
    );
    return jsonb_build_object(
      'allowed', false,
      'retry_after_seconds', v_retry,
      'limit', v_limit
    );
  end if;

  insert into public.auth_rate_limit_events(action, identifier_hash, user_agent_hash)
  values(v_action, v_identifier_hash, v_user_agent_hash);

  delete from public.auth_rate_limit_events
  where created_at < now() - interval '7 days';

  return jsonb_build_object(
    'allowed', true,
    'retry_after_seconds', 0,
    'limit', v_limit,
    'remaining', greatest(0, v_limit - v_count - 1)
  );
end
$$;

revoke all on function public.check_auth_rate_limit(text,text,text) from public;
grant execute on function public.check_auth_rate_limit(text,text,text) to anon, authenticated;
