-- Non-operational hardening + first-party visitor analytics.
-- This migration intentionally avoids cash, sales, stock and active-session tables.

drop policy if exists landing_page_content_public_read on public.landing_page_content;
create policy landing_page_content_public_read
on public.landing_page_content
for select
to anon, authenticated
using (id = 'adega-pro');

grant select (id, content) on public.landing_page_content to anon, authenticated;

create or replace function public.get_landing_page_content()
returns jsonb
language sql
security invoker
set search_path to ''
as $function$
  select coalesce(
    (select content from public.landing_page_content where id='adega-pro'),
    '{}'::jsonb
  )
$function$;

revoke execute on function public.get_landing_page_content() from public;
grant execute on function public.get_landing_page_content() to anon, authenticated, service_role;

create table if not exists public.landing_visits (
  id bigint generated by default as identity primary key,
  visitor_key text not null,
  request_path text not null,
  referrer_hostname text,
  device_type text,
  country text,
  created_at timestamptz not null default now(),
  constraint landing_visits_visitor_key_len check (char_length(visitor_key) between 8 and 128),
  constraint landing_visits_path_len check (char_length(request_path) between 1 and 512)
);

alter table public.landing_visits enable row level security;

drop policy if exists landing_visits_no_direct_access on public.landing_visits;
create policy landing_visits_no_direct_access
on public.landing_visits
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

revoke all on public.landing_visits from public, anon, authenticated;
grant select, insert on public.landing_visits to service_role;

create index if not exists landing_visits_created_at_idx on public.landing_visits(created_at desc);
create index if not exists landing_visits_visitor_created_idx on public.landing_visits(visitor_key,created_at desc);
create index if not exists landing_visits_path_created_idx on public.landing_visits(request_path,created_at desc);

create or replace function public.get_landing_analytics_service(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_days integer := least(90,greatest(1,coalesce(p_days,30)));
  v_since timestamptz := now() - make_interval(days => least(90,greatest(1,coalesce(p_days,30))));
  v_count jsonb;
  v_paths jsonb;
  v_refs jsonb;
  v_devices jsonb;
  v_countries jsonb;
begin
  select jsonb_build_object(
    'visitors',count(distinct visitor_key),
    'pageviews',count(*)
  ) into v_count
  from public.landing_visits
  where created_at >= v_since;

  select coalesce(jsonb_agg(x order by (x->>'pageviews')::bigint desc),'[]'::jsonb)
  into v_paths
  from (
    select jsonb_build_object('requestPath',request_path,'pageviews',count(*)) x
    from public.landing_visits
    where created_at >= v_since
    group by request_path
    order by count(*) desc
    limit 10
  ) q;

  select coalesce(jsonb_agg(x order by (x->>'pageviews')::bigint desc),'[]'::jsonb)
  into v_refs
  from (
    select jsonb_build_object('referrerHostname',coalesce(nullif(referrer_hostname,''),'Direto'),'pageviews',count(*)) x
    from public.landing_visits
    where created_at >= v_since
    group by coalesce(nullif(referrer_hostname,''),'Direto')
    order by count(*) desc
    limit 10
  ) q;

  select coalesce(jsonb_agg(x order by (x->>'pageviews')::bigint desc),'[]'::jsonb)
  into v_devices
  from (
    select jsonb_build_object('deviceType',coalesce(nullif(device_type,''),'Desconhecido'),'pageviews',count(*)) x
    from public.landing_visits
    where created_at >= v_since
    group by coalesce(nullif(device_type,''),'Desconhecido')
    order by count(*) desc
    limit 10
  ) q;

  select coalesce(jsonb_agg(x order by (x->>'pageviews')::bigint desc),'[]'::jsonb)
  into v_countries
  from (
    select jsonb_build_object('country',coalesce(nullif(country,''),'Não informado'),'pageviews',count(*)) x
    from public.landing_visits
    where created_at >= v_since and nullif(country,'') is not null
    group by country
    order by count(*) desc
    limit 10
  ) q;

  return jsonb_build_object(
    'days',v_days,
    'count',coalesce(v_count,'{"visitors":0,"pageviews":0}'::jsonb),
    'paths',v_paths,
    'referrers',v_refs,
    'devices',v_devices,
    'countries',v_countries,
    'source','FIRST_PARTY'
  );
end
$function$;

revoke execute on function public.get_landing_analytics_service(integer) from public, anon, authenticated;
grant execute on function public.get_landing_analytics_service(integer) to service_role;

drop policy if exists platform_admin_self_read on public.platform_admins;
create policy platform_admin_self_read
on public.platform_admins
for select
to authenticated
using (user_id = (select auth.uid()));

drop index if exists public.platform_sales_partners_email_lower_uidx;
