-- Administrative audit trail for seller approvals/status changes.
create table if not exists public.platform_partner_admin_audit (
  id bigint generated by default as identity primary key,
  partner_id uuid not null references public.platform_sales_partners(id) on delete cascade,
  action text not null,
  previous_status text,
  new_status text,
  actor_user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.platform_partner_admin_audit enable row level security;
revoke all on public.platform_partner_admin_audit from public,anon,authenticated;
grant select,insert on public.platform_partner_admin_audit to service_role;

create index if not exists platform_partner_admin_audit_partner_created_idx
  on public.platform_partner_admin_audit(partner_id,created_at desc);

create or replace function public.set_platform_sales_partner_status(p_id uuid,p_status text)
returns void
language plpgsql
security definer
set search_path='public','private','auth'
as $function$
declare
  v_status text:=upper(trim(coalesce(p_status,'')));
  v_previous text;
begin
  if auth.uid() is null or not private.is_super_admin() then raise exception 'forbidden'; end if;
  if v_status not in ('PENDENTE','ATIVO','SUSPENSO','CANCELADO') then raise exception 'status inválido'; end if;

  select registration_status into v_previous
  from public.platform_sales_partners
  where id=p_id
  for update;

  if v_previous is null then raise exception 'vendedor não encontrado'; end if;

  update public.platform_sales_partners
  set registration_status=v_status,
      active=(v_status='ATIVO'),
      approved_at=case when v_status='ATIVO' then now() else approved_at end,
      approved_by=case when v_status='ATIVO' then auth.uid() else approved_by end,
      updated_at=now()
  where id=p_id;

  insert into public.platform_partner_admin_audit(
    partner_id,action,previous_status,new_status,actor_user_id
  ) values(
    p_id,
    case when v_status='ATIVO' and v_previous='PENDENTE' then 'APROVADO'
         when v_status='ATIVO' then 'REATIVADO'
         when v_status='SUSPENSO' then 'SUSPENSO'
         when v_status='CANCELADO' then 'CANCELADO'
         else 'PENDENTE' end,
    v_previous,v_status,auth.uid()
  );
end;
$function$;

revoke all on function public.set_platform_sales_partner_status(uuid,text) from public,anon;
grant execute on function public.set_platform_sales_partner_status(uuid,text) to authenticated;
