-- Seller security improvements: pending profile changes, access audit and admin review.
-- Additive only; does not touch tenant/client operational tables.

alter table public.platform_sales_partners
  add column if not exists pending_phone text,
  add column if not exists pending_pix_key text,
  add column if not exists profile_change_requested_at timestamptz;

create table if not exists public.platform_partner_access_audit (
  id bigint generated by default as identity primary key,
  partner_id uuid not null references public.platform_sales_partners(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('LOGIN','SESSION_REFRESH','PROFILE_CHANGE_REQUEST')),
  device text,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now()
);

alter table public.platform_partner_access_audit enable row level security;
revoke all on public.platform_partner_access_audit from public,anon,authenticated;
grant select,insert on public.platform_partner_access_audit to service_role;

create index if not exists platform_partner_access_partner_created_idx
  on public.platform_partner_access_audit(partner_id,created_at desc);

create or replace function public.record_my_partner_access(p_event text default 'LOGIN',p_device text default null)
returns void
language plpgsql
security definer
set search_path='public','auth','extensions'
as $function$
declare
  v_uid uuid:=auth.uid();
  v_partner uuid;
  v_headers jsonb:=coalesce(nullif(current_setting('request.headers',true),'')::jsonb,'{}'::jsonb);
  v_ip text;
  v_ua text;
  v_event text:=upper(trim(coalesce(p_event,'LOGIN')));
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  if v_event not in ('LOGIN','SESSION_REFRESH','PROFILE_CHANGE_REQUEST') then raise exception 'evento inválido'; end if;

  select id into v_partner from public.platform_sales_partners where auth_user_id=v_uid limit 1;
  if v_partner is null then return; end if;

  v_ip:=coalesce(v_headers->>'x-forwarded-for',v_headers->>'x-real-ip','');
  v_ua:=left(coalesce(v_headers->>'user-agent',''),500);

  insert into public.platform_partner_access_audit(partner_id,auth_user_id,event_type,device,user_agent,ip_hash)
  values(
    v_partner,v_uid,v_event,left(nullif(trim(p_device),''),120),nullif(v_ua,''),
    case when v_ip='' then null else encode(extensions.digest(v_ip,'sha256'),'hex') end
  );
end;
$function$;

revoke all on function public.record_my_partner_access(text,text) from public,anon;
grant execute on function public.record_my_partner_access(text,text) to authenticated;

create or replace function public.update_my_partner_profile(p_payload jsonb)
returns void
language plpgsql
security definer
set search_path='public','auth'
as $function$
declare
  v_uid uuid := auth.uid();
  v_mode text := coalesce(p_payload->>'payout_mode','IMEDIATO');
  v_day integer := coalesce((p_payload->>'monthly_payout_day')::integer,5);
  v_phone text:=nullif(trim(p_payload->>'phone'),'');
  v_pix text:=nullif(trim(p_payload->>'pix_key'),'');
  v_current public.platform_sales_partners%rowtype;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  if v_mode not in ('IMEDIATO','FECHAMENTO_MENSAL') then raise exception 'modo inválido'; end if;
  v_day := greatest(1,least(v_day,28));

  select * into v_current
  from public.platform_sales_partners
  where auth_user_id=v_uid and active=true and registration_status='ATIVO'
  limit 1
  for update;

  if v_current.id is null then raise exception 'vendedor não autorizado'; end if;

  update public.platform_sales_partners
  set pending_phone=case when v_phone is distinct from v_current.phone then v_phone else pending_phone end,
      pending_pix_key=case when v_pix is distinct from v_current.pix_key then v_pix else pending_pix_key end,
      profile_change_requested_at=case when (v_phone is distinct from v_current.phone) or (v_pix is distinct from v_current.pix_key) then now() else profile_change_requested_at end,
      payout_mode=v_mode,
      monthly_payout_day=v_day,
      updated_at=now()
  where id=v_current.id;

  if (v_phone is distinct from v_current.phone) or (v_pix is distinct from v_current.pix_key) then
    perform public.record_my_partner_access('PROFILE_CHANGE_REQUEST','portal');
  end if;
end;
$function$;

revoke all on function public.update_my_partner_profile(jsonb) from public,anon;
grant execute on function public.update_my_partner_profile(jsonb) to authenticated;

create or replace function public.review_platform_partner_profile_change(p_partner_id uuid,p_approve boolean)
returns void
language plpgsql
security definer
set search_path='public','private','auth'
as $function$
declare
  v_partner public.platform_sales_partners%rowtype;
begin
  if auth.uid() is null or not private.is_super_admin() then raise exception 'forbidden'; end if;

  select * into v_partner from public.platform_sales_partners where id=p_partner_id for update;
  if v_partner.id is null then raise exception 'vendedor não encontrado'; end if;
  if v_partner.pending_phone is null and v_partner.pending_pix_key is null then raise exception 'não há alteração pendente'; end if;

  if p_approve then
    update public.platform_sales_partners
    set phone=coalesce(pending_phone,phone),
        pix_key=coalesce(pending_pix_key,pix_key),
        pending_phone=null,
        pending_pix_key=null,
        profile_change_requested_at=null,
        updated_at=now()
    where id=p_partner_id;
  else
    update public.platform_sales_partners
    set pending_phone=null,pending_pix_key=null,profile_change_requested_at=null,updated_at=now()
    where id=p_partner_id;
  end if;

  insert into public.platform_partner_admin_audit(partner_id,action,previous_status,new_status,actor_user_id)
  values(p_partner_id,case when p_approve then 'ALTERACAO_PERFIL_APROVADA' else 'ALTERACAO_PERFIL_REJEITADA' end,
         v_partner.registration_status,v_partner.registration_status,auth.uid());
end;
$function$;

revoke all on function public.review_platform_partner_profile_change(uuid,boolean) from public,anon;
grant execute on function public.review_platform_partner_profile_change(uuid,boolean) to authenticated;

create or replace function public.get_platform_partner_security_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path='public','private','auth'
as $function$
declare result jsonb;
begin
  if auth.uid() is null or not private.is_super_admin() then raise exception 'forbidden'; end if;

  select jsonb_build_object(
    'pending_profile_changes',coalesce((
      select jsonb_agg(jsonb_build_object(
        'partner_id',p.id,'full_name',p.full_name,'email',p.email,
        'current_phone',p.phone,'pending_phone',p.pending_phone,
        'current_pix_key',p.pix_key,'pending_pix_key',p.pending_pix_key,
        'requested_at',p.profile_change_requested_at
      ) order by p.profile_change_requested_at desc)
      from public.platform_sales_partners p
      where p.pending_phone is not null or p.pending_pix_key is not null
    ),'[]'::jsonb),
    'admin_audit',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',a.id,'partner_id',a.partner_id,'action',a.action,
        'previous_status',a.previous_status,'new_status',a.new_status,'created_at',a.created_at
      ) order by a.created_at desc)
      from (select * from public.platform_partner_admin_audit order by created_at desc limit 200) a
    ),'[]'::jsonb),
    'access_audit',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',x.id,'partner_id',x.partner_id,'event_type',x.event_type,
        'device',x.device,'user_agent',x.user_agent,'ip_hash',x.ip_hash,'created_at',x.created_at
      ) order by x.created_at desc)
      from (select * from public.platform_partner_access_audit order by created_at desc limit 200) x
    ),'[]'::jsonb)
  ) into result;
  return result;
end;
$function$;

revoke all on function public.get_platform_partner_security_snapshot() from public,anon;
grant execute on function public.get_platform_partner_security_snapshot() to authenticated;
