-- Seller session guard, referral rate limit and isolation health audit.

create table if not exists public.platform_partner_sessions (
  id bigint generated by default as identity primary key,
  partner_id uuid not null references public.platform_sales_partners(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  session_key_hash text not null,
  device text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  closed_at timestamptz,
  unique(partner_id,session_key_hash)
);

alter table public.platform_partner_sessions enable row level security;
revoke all on public.platform_partner_sessions from public,anon,authenticated;
grant select,insert,update on public.platform_partner_sessions to service_role;

create index if not exists platform_partner_sessions_partner_seen_idx
  on public.platform_partner_sessions(partner_id,last_seen_at desc);

create or replace function public.touch_my_partner_session(p_session_key text,p_device text default null)
returns jsonb
language plpgsql
security definer
set search_path='public','auth','extensions'
as $function$
declare
  v_uid uuid:=auth.uid();
  v_partner uuid;
  v_hash text;
  v_active integer;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  if length(trim(coalesce(p_session_key,'')))<16 then raise exception 'sessão inválida'; end if;

  select id into v_partner
  from public.platform_sales_partners
  where auth_user_id=v_uid and active=true and registration_status='ATIVO'
  limit 1;

  if v_partner is null then raise exception 'vendedor não autorizado'; end if;

  v_hash:=encode(extensions.digest(trim(p_session_key),'sha256'),'hex');

  if not exists(
    select 1 from public.platform_partner_sessions
    where partner_id=v_partner and session_key_hash=v_hash and closed_at is null
  ) then
    select count(*) into v_active
    from public.platform_partner_sessions
    where partner_id=v_partner
      and closed_at is null
      and last_seen_at>now()-interval '30 minutes';

    if v_active>=2 then
      raise exception 'limite de 2 sessões simultâneas atingido';
    end if;
  end if;

  insert into public.platform_partner_sessions(partner_id,auth_user_id,session_key_hash,device,last_seen_at,closed_at)
  values(v_partner,v_uid,v_hash,left(nullif(trim(p_device),''),120),now(),null)
  on conflict(partner_id,session_key_hash)
  do update set last_seen_at=excluded.last_seen_at,device=excluded.device,closed_at=null;

  return jsonb_build_object('ok',true,'active_sessions',(
    select count(*) from public.platform_partner_sessions
    where partner_id=v_partner and closed_at is null and last_seen_at>now()-interval '30 minutes'
  ));
end;
$function$;

create or replace function public.close_my_partner_session(p_session_key text)
returns void
language plpgsql
security definer
set search_path='public','auth','extensions'
as $function$
declare
  v_uid uuid:=auth.uid();
  v_hash text;
begin
  if v_uid is null then return; end if;
  if length(trim(coalesce(p_session_key,'')))<16 then return; end if;
  v_hash:=encode(extensions.digest(trim(p_session_key),'sha256'),'hex');
  update public.platform_partner_sessions
  set closed_at=now(),last_seen_at=now()
  where auth_user_id=v_uid and session_key_hash=v_hash and closed_at is null;
end;
$function$;

revoke all on function public.touch_my_partner_session(text,text) from public,anon;
grant execute on function public.touch_my_partner_session(text,text) to authenticated;
revoke all on function public.close_my_partner_session(text) from public,anon;
grant execute on function public.close_my_partner_session(text) to authenticated;

create table if not exists public.platform_partner_action_rate (
  partner_id uuid not null references public.platform_sales_partners(id) on delete cascade,
  action_key text not null,
  window_started_at timestamptz not null default now(),
  action_count integer not null default 0,
  primary key(partner_id,action_key)
);

alter table public.platform_partner_action_rate enable row level security;
revoke all on public.platform_partner_action_rate from public,anon,authenticated;
grant select,insert,update on public.platform_partner_action_rate to service_role;

create or replace function public.save_my_partner_referral(p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path='public','auth'
as $function$
declare
  v_uid uuid := auth.uid();
  v_partner public.platform_sales_partners%rowtype;
  v_id uuid;
  v_type text;
  v_rate public.platform_partner_action_rate%rowtype;
begin
  if v_uid is null then raise exception 'authentication required'; end if;

  select * into v_partner
  from public.platform_sales_partners
  where auth_user_id=v_uid and active=true and registration_status='ATIVO'
  limit 1;

  if v_partner.id is null then raise exception 'vendedor não autorizado'; end if;

  insert into public.platform_partner_action_rate(partner_id,action_key,window_started_at,action_count)
  values(v_partner.id,'CREATE_REFERRAL',now(),1)
  on conflict(partner_id,action_key) do nothing;

  select * into v_rate from public.platform_partner_action_rate
  where partner_id=v_partner.id and action_key='CREATE_REFERRAL'
  for update;

  if v_rate.window_started_at < now()-interval '1 hour' then
    update public.platform_partner_action_rate
    set window_started_at=now(),action_count=1
    where partner_id=v_partner.id and action_key='CREATE_REFERRAL';
  elsif v_rate.action_count>=120 then
    raise exception 'limite temporário de indicações atingido; tente novamente mais tarde';
  else
    update public.platform_partner_action_rate
    set action_count=action_count+1
    where partner_id=v_partner.id and action_key='CREATE_REFERRAL';
  end if;

  v_type := coalesce(p_payload->>'referral_type','ASSINATURA');
  if v_type not in ('ASSINATURA','PERSONALIZADO') then raise exception 'tipo inválido'; end if;
  if nullif(trim(p_payload->>'lead_name'),'') is null then raise exception 'nome do lead obrigatório'; end if;

  insert into public.platform_partner_referrals(
    partner_id,referral_type,lead_name,lead_email,lead_phone,status,source,
    estimated_value,converted_value,notes
  ) values(
    v_partner.id,v_type,trim(p_payload->>'lead_name'),
    nullif(lower(trim(p_payload->>'lead_email')),''),
    nullif(trim(p_payload->>'lead_phone'),''),
    'LEAD','PARTNER_PORTAL',
    case when v_type='PERSONALIZADO' then 990 else 149 end,
    0,nullif(trim(p_payload->>'notes'),'')
  ) returning id into v_id;

  return v_id;
end;
$function$;

revoke all on function public.save_my_partner_referral(jsonb) from public,anon;
grant execute on function public.save_my_partner_referral(jsonb) to authenticated;

create or replace function public.audit_partner_isolation_health()
returns jsonb
language plpgsql
stable
security definer
set search_path='public','private','auth'
as $function$
declare
  v_tables text[]:=array['platform_sales_partners','platform_partner_referrals','platform_partner_commissions','platform_partner_invites','platform_partner_policies','platform_partner_admin_audit','platform_partner_access_audit','platform_partner_sessions','platform_partner_action_rate'];
begin
  if auth.uid() is null or not private.is_super_admin() then raise exception 'forbidden'; end if;

  return jsonb_build_object(
    'checked_at',now(),
    'direct_authenticated_select_tables',coalesce((
      select jsonb_agg(t)
      from unnest(v_tables) t
      where has_table_privilege('authenticated',format('public.%I',t),'select')
    ),'[]'::jsonb),
    'direct_anon_select_tables',coalesce((
      select jsonb_agg(t)
      from unnest(v_tables) t
      where has_table_privilege('anon',format('public.%I',t),'select')
    ),'[]'::jsonb),
    'duplicate_email_count',(select count(*) from (select lower(email) from public.platform_sales_partners group by lower(email) having count(*)>1) x),
    'duplicate_auth_user_count',(select count(*) from (select auth_user_id from public.platform_sales_partners where auth_user_id is not null group by auth_user_id having count(*)>1) x),
    'orphan_referrals',(select count(*) from public.platform_partner_referrals r left join public.platform_sales_partners p on p.id=r.partner_id where p.id is null),
    'orphan_commissions',(select count(*) from public.platform_partner_commissions c left join public.platform_sales_partners p on p.id=c.partner_id where p.id is null),
    'pending_approvals',(select count(*) from public.platform_sales_partners where registration_status='PENDENTE'),
    'pending_profile_changes',(select count(*) from public.platform_sales_partners where pending_phone is not null or pending_pix_key is not null)
  );
end;
$function$;

revoke all on function public.audit_partner_isolation_health() from public,anon;
grant execute on function public.audit_partner_isolation_health() to authenticated;
