import React,{useEffect,useState} from 'react';
import { Receipt, RefreshCw, Eye, X, CreditCard, Package, Ban, Pencil } from 'lucide-react';
import { productionDb } from '../../services/productionDb';
import { EmptyState, MetricCard, PageHeader, StatusBadge } from '../ui/ProUi';

export const ProductionSalesHistoryView:React.FC=()=>{
 const[rows,setRows]=useState<any[]>([]);
 const[busy,setBusy]=useState(false);
 const[error,setError]=useState('');
 const[details,setDetails]=useState<any>(null);
 const[editing,setEditing]=useState<any>(null);
 const[editDiscount,setEditDiscount]=useState('0');
 const[editMethod,setEditMethod]=useState('DINHEIRO');

 const load=async()=>{setBusy(true);setError('');try{setRows(await productionDb.getSales());}catch(e:any){setError(e?.message||'Falha ao carregar vendas.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);

 const cancelSale=async(r:any)=>{const reason=window.prompt('Motivo obrigatório para cancelar a venda #'+r.sale_number+':');if(!reason?.trim())return;if(!window.confirm('Cancelar a venda e estornar estoque, caixa e financeiro?'))return;setBusy(true);setError('');try{await productionDb.cancelSale(r.id,reason.trim());setDetails(null);await load();}catch(e:any){setError(e?.message||'Falha ao cancelar a venda.');}finally{setBusy(false);}};
 const beginEdit=async(r:any)=>{setBusy(true);setError('');try{const d=await productionDb.getSaleDetails(r.id);const pays=d?.payments||[];if(pays.length!==1){setError('Venda com pagamento múltiplo exige ajuste detalhado.');return;}setEditing(d);setEditDiscount(String(Number(d.sale?.discount||0).toFixed(2)));setEditMethod(pays[0]?.method||'DINHEIRO');}catch(e:any){setError(e?.message||'Falha ao abrir alteração.');}finally{setBusy(false);}};
 const saveEdit=async()=>{if(!editing?.sale)return;const discount=Number(editDiscount.replace(',','.'));if(!Number.isFinite(discount)||discount<0){setError('Desconto inválido.');return;}setBusy(true);setError('');try{if(discount!==Number(editing.sale.discount||0))await productionDb.updateSaleDiscount(editing.sale.id,discount);const current=editing.payments?.[0]?.method;if(editMethod!==current)await productionDb.updateSalePaymentMethod(editing.sale.id,editMethod as any);setEditing(null);await load();}catch(e:any){setError(e?.message||'Falha ao salvar alterações.');}finally{setBusy(false);}};

 const open=async(id:string)=>{setBusy(true);setError('');try{setDetails(await productionDb.getSaleDetails(id));}catch(e:any){setError(e?.message||'Falha ao abrir o cupom.');}finally{setBusy(false);}};

 const paid=rows.filter(r=>r.status==='PAGA'); const revenue=paid.reduce((s,r)=>s+Number(r.total||0),0); const ticket=paid.length?revenue/paid.length:0;
 return <div className="flex-1 p-3 sm:p-4 lg:p-6 overflow-y-auto space-y-5 text-white">
  <PageHeader eyebrow="Vendas" title="Vendas & cupons" description="Histórico real com itens, pagamentos, operador, cupom e rastreabilidade." actions={<button disabled={busy} onClick={()=>void load()} className="px-3 py-2 rounded-xl border border-neutral-700 text-xs text-neutral-300 flex items-center gap-2"><RefreshCw size={14}/>Atualizar</button>}/>
  {error&&<div className="p-3 rounded-xl border border-rose-800 bg-rose-950/40 text-rose-300 text-xs">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MetricCard label="Vendas pagas" value={paid.length} icon={Receipt}/><MetricCard label="Faturamento" value={'R$ '+revenue.toLocaleString('pt-BR',{minimumFractionDigits:2})} icon={CreditCard} tone="emerald"/><MetricCard label="Ticket médio" value={'R$ '+ticket.toLocaleString('pt-BR',{minimumFractionDigits:2})} icon={Package} tone="sky"/><MetricCard label="Cupons registrados" value={rows.length} icon={Receipt}/></div>
  {rows.length===0?<EmptyState title="Nenhuma venda registrada" description="Os cupons aparecerão aqui assim que o PDV concluir vendas no ambiente de produção."/>:<div className="bg-neutral-900 border border-neutral-800 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-neutral-950/70 text-neutral-400 uppercase"><tr><th className="p-3">Venda</th><th className="p-3">Data</th><th className="p-3">Usuário / turno</th><th className="p-3">Status</th><th className="p-3 text-right">Desconto</th><th className="p-3 text-right">Total</th><th className="p-3"></th></tr></thead><tbody className="divide-y divide-neutral-800">
   {rows.map(r=><tr key={r.id}><td className="p-3 font-mono text-white">#{r.sale_number}</td><td className="p-3 text-neutral-300">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3"><div className="font-bold text-white">{r.operator_name||'Operador'}</div><div className="text-[10px] text-neutral-500 mt-1">{r.shift_opened_at?'Turno · '+new Date(r.shift_opened_at).toLocaleString('pt-BR')+(r.shift_status==='ABERTO'?' · ABERTO':''):'Turno não identificado'}</div></td><td className="p-3"><StatusBadge tone={r.status==='PAGA'?'success':r.status==='CANCELADA'?'danger':'neutral'}>{r.status}</StatusBadge></td><td className="p-3 text-right font-mono">R$ {Number(r.discount||0).toFixed(2)}</td><td className="p-3 text-right font-mono font-black text-amber-400">R$ {Number(r.total||0).toFixed(2)}</td><td className="p-3 text-right"><div className="inline-flex flex-wrap justify-end gap-1"><button onClick={()=>void open(r.id)} className="px-2.5 py-1.5 rounded-lg bg-neutral-800 text-neutral-200 inline-flex items-center gap-1"><Eye size={13}/>Cupom</button>{r.status==='PAGA'&&<><button onClick={()=>void beginEdit(r)} className="px-2.5 py-1.5 rounded-lg border border-sky-800 text-sky-300 inline-flex items-center gap-1"><Pencil size={13}/>Alterar</button><button onClick={()=>void cancelSale(r)} className="px-2.5 py-1.5 rounded-lg border border-rose-800 text-rose-300 inline-flex items-center gap-1"><Ban size={13}/>Cancelar</button></>}</div></td></tr>)}
  </tbody></table></div></div>}

  {editing&&<div className="fixed inset-0 z-[60] bg-black/90 backdrop-blur-sm grid place-items-center p-3"><div className="w-full max-w-xl rounded-3xl bg-[#111] border border-neutral-700 shadow-2xl overflow-hidden"><div className="p-5 border-b border-neutral-800 flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-[.2em] text-amber-400 font-black">Correção administrativa</div><h2 className="text-xl font-black mt-1">Alterar venda #{editing.sale?.sale_number}</h2><p className="text-xs text-neutral-500 mt-1">Corrija desconto ou forma de pagamento. Caixa e totais serão sincronizados.</p></div><button onClick={()=>setEditing(null)} className="p-2 rounded-xl bg-neutral-900"><X size={18}/></button></div><div className="p-5 space-y-5"><div><label className="text-xs font-bold text-neutral-400">Forma de pagamento correta</label><div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mt-2">{['DINHEIRO','PIX','DEBITO','CREDITO','VOUCHER','FIADO'].map(m=><button key={m} onClick={()=>setEditMethod(m)} className={'p-3 rounded-xl border text-xs font-black '+(editMethod===m?'border-amber-400 bg-amber-400/10 text-amber-300':'border-neutral-800 bg-neutral-950 text-neutral-400')}>{m}</button>)}</div></div><div><label className="text-xs font-bold text-neutral-400">Desconto da venda (R$)</label><input value={editDiscount} onChange={e=>setEditDiscount(e.target.value)} inputMode="decimal" className="mt-2 w-full rounded-xl bg-neutral-950 border border-neutral-700 px-4 py-3 text-white font-mono"/></div><div className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 text-xs text-neutral-400">Total atual: <b className="text-white">R$ {Number(editing.sale?.total||0).toFixed(2)}</b> · Pagamento registrado: <b className="text-white">{editing.payments?.[0]?.method||'—'}</b></div></div><div className="p-5 border-t border-neutral-800 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="px-4 py-2.5 rounded-xl border border-neutral-700 text-sm">Cancelar</button><button disabled={busy} onClick={()=>void saveEdit()} className="px-5 py-2.5 rounded-xl bg-amber-400 text-black font-black text-sm">{busy?'Salvando...':'Salvar correção'}</button></div></div></div>}

  {details&&<div className="fixed inset-0 z-50 bg-black/85 grid place-items-center p-3"><div className="w-full max-w-3xl max-h-[94dvh] overflow-y-auto rounded-2xl bg-neutral-900 border border-neutral-800 p-5">
    <div className="flex items-start justify-between gap-3 pb-4 border-b border-neutral-800"><div><h2 className="text-lg font-black">Cupom #{details.sale?.sale_number}</h2><p className="text-xs text-neutral-500 mt-1">{new Date(details.sale?.created_at).toLocaleString('pt-BR')} · {details.operator?.name||'Operador'}</p></div><button onClick={()=>setDetails(null)}><X size={18}/></button></div>
    <div className="mt-4 space-y-2"><div className="text-xs font-black text-neutral-400 uppercase tracking-wider flex items-center gap-2"><Package size={14}/>Itens</div>{(details.items||[]).map((i:any)=><div key={i.id} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 text-xs"><div className="flex justify-between gap-3"><strong>{i.product_name}</strong><span className="font-mono font-bold">R$ {Number(i.subtotal||0).toFixed(2)}</span></div><div className="text-neutral-500 mt-1">{Number(i.quantity)} × R$ {Number(i.unit_price||0).toFixed(2)}{Number(i.discount||0)>0?` · desconto R$ ${Number(i.discount).toFixed(2)}`:''}</div></div>)}</div>
    <div className="mt-5 space-y-2"><div className="text-xs font-black text-neutral-400 uppercase tracking-wider flex items-center gap-2"><CreditCard size={14}/>Pagamentos</div>{(details.payments||[]).map((p:any)=><div key={p.id} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 text-xs flex flex-wrap justify-between gap-2"><span>{p.method} · {p.provider||'MANUAL'}</span><span className="font-mono font-bold">R$ {Number(p.amount||0).toFixed(2)}{Number(p.change_amount||0)>0?` · troco R$ ${Number(p.change_amount).toFixed(2)}`:''}</span>{(p.authorization_code||p.nsu)&&<span className="w-full text-neutral-500">Autorização {p.authorization_code||'—'} · NSU {p.nsu||'—'}</span>}</div>)}</div>
    {(details.batch_consumptions||[]).length>0&&<div className="mt-5"><div className="text-xs font-black text-neutral-400 uppercase tracking-wider">Rastreabilidade de lote</div><div className="mt-2 grid sm:grid-cols-2 gap-2">{details.batch_consumptions.map((b:any,idx:number)=><div key={idx} className="p-3 rounded-xl bg-neutral-950 border border-neutral-800 text-[11px] text-neutral-400">Lote {b.lot_number||'—'} · qtd {Number(b.quantity)} · validade {b.expiry_date?new Date(b.expiry_date+'T00:00:00').toLocaleDateString('pt-BR'):'—'}</div>)}</div></div>}
    <div className="mt-5 p-4 rounded-xl bg-neutral-950 border border-neutral-800 space-y-2"><div className="flex justify-between text-xs text-neutral-400"><span>Subtotal</span><span>R$ {Number(details.sale?.subtotal||0).toFixed(2)}</span></div><div className="flex justify-between text-xs text-neutral-400"><span>Desconto</span><span>- R$ {Number(details.sale?.discount||0).toFixed(2)}</span></div><div className="flex justify-between text-lg font-black pt-2 border-t border-neutral-800"><span>Total</span><span className="text-amber-400">R$ {Number(details.sale?.total||0).toFixed(2)}</span></div></div>
  </div></div>}
 </div>;
};